package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * AFlowTemp generated by hbm2java
 */
public class AFlowTemp implements java.io.Serializable {

	private AFlowTempId id;

	public AFlowTemp() {
	}

	public AFlowTemp(AFlowTempId id) {
		this.id = id;
	}

	public AFlowTempId getId() {
		return this.id;
	}

	public void setId(AFlowTempId id) {
		this.id = id;
	}

}
