package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * AssignerNew generated by hbm2java
 */
public class AssignerNew implements java.io.Serializable {

	private AssignerNewId id;

	public AssignerNew() {
	}

	public AssignerNew(AssignerNewId id) {
		this.id = id;
	}

	public AssignerNewId getId() {
		return this.id;
	}

	public void setId(AssignerNewId id) {
		this.id = id;
	}

}
