package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * Assigner generated by hbm2java
 */
public class Assigner implements java.io.Serializable {

	private AssignerId id;

	public Assigner() {
	}

	public Assigner(AssignerId id) {
		this.id = id;
	}

	public AssignerId getId() {
		return this.id;
	}

	public void setId(AssignerId id) {
		this.id = id;
	}

}
