package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * AssignerN1 generated by hbm2java
 */
public class AssignerN1 implements java.io.Serializable {

	private AssignerN1Id id;

	public AssignerN1() {
	}

	public AssignerN1(AssignerN1Id id) {
		this.id = id;
	}

	public AssignerN1Id getId() {
		return this.id;
	}

	public void setId(AssignerN1Id id) {
		this.id = id;
	}

}
