package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AssignerNewId generated by hbm2java
 */
public class AssignerNewId implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal fkOrg;
	private BigDecimal fkOrg1;
	private String fkUsl;
	private String mg1;
	private String mg2;
	private String nd;
	private String fkUslm;
	private BigDecimal typeRow;
	private String kul;
	private BigDecimal typRec;
	private String reu;

	public AssignerNewId() {
	}

	public AssignerNewId(BigDecimal id, BigDecimal fkOrg, BigDecimal fkOrg1,
			String fkUsl, String mg1, String mg2, String nd, String fkUslm,
			BigDecimal typeRow, String kul, BigDecimal typRec, String reu) {
		this.id = id;
		this.fkOrg = fkOrg;
		this.fkOrg1 = fkOrg1;
		this.fkUsl = fkUsl;
		this.mg1 = mg1;
		this.mg2 = mg2;
		this.nd = nd;
		this.fkUslm = fkUslm;
		this.typeRow = typeRow;
		this.kul = kul;
		this.typRec = typRec;
		this.reu = reu;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getFkOrg() {
		return this.fkOrg;
	}

	public void setFkOrg(BigDecimal fkOrg) {
		this.fkOrg = fkOrg;
	}

	public BigDecimal getFkOrg1() {
		return this.fkOrg1;
	}

	public void setFkOrg1(BigDecimal fkOrg1) {
		this.fkOrg1 = fkOrg1;
	}

	public String getFkUsl() {
		return this.fkUsl;
	}

	public void setFkUsl(String fkUsl) {
		this.fkUsl = fkUsl;
	}

	public String getMg1() {
		return this.mg1;
	}

	public void setMg1(String mg1) {
		this.mg1 = mg1;
	}

	public String getMg2() {
		return this.mg2;
	}

	public void setMg2(String mg2) {
		this.mg2 = mg2;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getFkUslm() {
		return this.fkUslm;
	}

	public void setFkUslm(String fkUslm) {
		this.fkUslm = fkUslm;
	}

	public BigDecimal getTypeRow() {
		return this.typeRow;
	}

	public void setTypeRow(BigDecimal typeRow) {
		this.typeRow = typeRow;
	}

	public String getKul() {
		return this.kul;
	}

	public void setKul(String kul) {
		this.kul = kul;
	}

	public BigDecimal getTypRec() {
		return this.typRec;
	}

	public void setTypRec(BigDecimal typRec) {
		this.typRec = typRec;
	}

	public String getReu() {
		return this.reu;
	}

	public void setReu(String reu) {
		this.reu = reu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssignerNewId))
			return false;
		AssignerNewId castOther = (AssignerNewId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getFkOrg() == castOther.getFkOrg()) || (this
						.getFkOrg() != null && castOther.getFkOrg() != null && this
						.getFkOrg().equals(castOther.getFkOrg())))
				&& ((this.getFkOrg1() == castOther.getFkOrg1()) || (this
						.getFkOrg1() != null && castOther.getFkOrg1() != null && this
						.getFkOrg1().equals(castOther.getFkOrg1())))
				&& ((this.getFkUsl() == castOther.getFkUsl()) || (this
						.getFkUsl() != null && castOther.getFkUsl() != null && this
						.getFkUsl().equals(castOther.getFkUsl())))
				&& ((this.getMg1() == castOther.getMg1()) || (this.getMg1() != null
						&& castOther.getMg1() != null && this.getMg1().equals(
						castOther.getMg1())))
				&& ((this.getMg2() == castOther.getMg2()) || (this.getMg2() != null
						&& castOther.getMg2() != null && this.getMg2().equals(
						castOther.getMg2())))
				&& ((this.getNd() == castOther.getNd()) || (this.getNd() != null
						&& castOther.getNd() != null && this.getNd().equals(
						castOther.getNd())))
				&& ((this.getFkUslm() == castOther.getFkUslm()) || (this
						.getFkUslm() != null && castOther.getFkUslm() != null && this
						.getFkUslm().equals(castOther.getFkUslm())))
				&& ((this.getTypeRow() == castOther.getTypeRow()) || (this
						.getTypeRow() != null && castOther.getTypeRow() != null && this
						.getTypeRow().equals(castOther.getTypeRow())))
				&& ((this.getKul() == castOther.getKul()) || (this.getKul() != null
						&& castOther.getKul() != null && this.getKul().equals(
						castOther.getKul())))
				&& ((this.getTypRec() == castOther.getTypRec()) || (this
						.getTypRec() != null && castOther.getTypRec() != null && this
						.getTypRec().equals(castOther.getTypRec())))
				&& ((this.getReu() == castOther.getReu()) || (this.getReu() != null
						&& castOther.getReu() != null && this.getReu().equals(
						castOther.getReu())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getFkOrg() == null ? 0 : this.getFkOrg().hashCode());
		result = 37 * result
				+ (getFkOrg1() == null ? 0 : this.getFkOrg1().hashCode());
		result = 37 * result
				+ (getFkUsl() == null ? 0 : this.getFkUsl().hashCode());
		result = 37 * result
				+ (getMg1() == null ? 0 : this.getMg1().hashCode());
		result = 37 * result
				+ (getMg2() == null ? 0 : this.getMg2().hashCode());
		result = 37 * result + (getNd() == null ? 0 : this.getNd().hashCode());
		result = 37 * result
				+ (getFkUslm() == null ? 0 : this.getFkUslm().hashCode());
		result = 37 * result
				+ (getTypeRow() == null ? 0 : this.getTypeRow().hashCode());
		result = 37 * result
				+ (getKul() == null ? 0 : this.getKul().hashCode());
		result = 37 * result
				+ (getTypRec() == null ? 0 : this.getTypRec().hashCode());
		result = 37 * result
				+ (getReu() == null ? 0 : this.getReu().hashCode());
		return result;
	}

}
