package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * DmfOrg generated by hbm2java
 */
public class DmfOrg implements java.io.Serializable {

	private DmfOrgId id;

	public DmfOrg() {
	}

	public DmfOrg(DmfOrgId id) {
		this.id = id;
	}

	public DmfOrgId getId() {
		return this.id;
	}

	public void setId(DmfOrgId id) {
		this.id = id;
	}

}
