package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ElementReestrId generated by hbm2java
 */
public class ElementReestrId implements java.io.Serializable {

	private BigDecimal elementIdLink;
	private BigDecimal valId;
	private BigDecimal valParentId;
	private BigDecimal fkAccessId;

	public ElementReestrId() {
	}

	public ElementReestrId(BigDecimal elementIdLink, BigDecimal valId,
			BigDecimal valParentId, BigDecimal fkAccessId) {
		this.elementIdLink = elementIdLink;
		this.valId = valId;
		this.valParentId = valParentId;
		this.fkAccessId = fkAccessId;
	}

	public BigDecimal getElementIdLink() {
		return this.elementIdLink;
	}

	public void setElementIdLink(BigDecimal elementIdLink) {
		this.elementIdLink = elementIdLink;
	}

	public BigDecimal getValId() {
		return this.valId;
	}

	public void setValId(BigDecimal valId) {
		this.valId = valId;
	}

	public BigDecimal getValParentId() {
		return this.valParentId;
	}

	public void setValParentId(BigDecimal valParentId) {
		this.valParentId = valParentId;
	}

	public BigDecimal getFkAccessId() {
		return this.fkAccessId;
	}

	public void setFkAccessId(BigDecimal fkAccessId) {
		this.fkAccessId = fkAccessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElementReestrId))
			return false;
		ElementReestrId castOther = (ElementReestrId) other;

		return ((this.getElementIdLink() == castOther.getElementIdLink()) || (this
				.getElementIdLink() != null
				&& castOther.getElementIdLink() != null && this
				.getElementIdLink().equals(castOther.getElementIdLink())))
				&& ((this.getValId() == castOther.getValId()) || (this
						.getValId() != null && castOther.getValId() != null && this
						.getValId().equals(castOther.getValId())))
				&& ((this.getValParentId() == castOther.getValParentId()) || (this
						.getValParentId() != null
						&& castOther.getValParentId() != null && this
						.getValParentId().equals(castOther.getValParentId())))
				&& ((this.getFkAccessId() == castOther.getFkAccessId()) || (this
						.getFkAccessId() != null
						&& castOther.getFkAccessId() != null && this
						.getFkAccessId().equals(castOther.getFkAccessId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getElementIdLink() == null ? 0 : this.getElementIdLink()
						.hashCode());
		result = 37 * result
				+ (getValId() == null ? 0 : this.getValId().hashCode());
		result = 37
				* result
				+ (getValParentId() == null ? 0 : this.getValParentId()
						.hashCode());
		result = 37
				* result
				+ (getFkAccessId() == null ? 0 : this.getFkAccessId()
						.hashCode());
		return result;
	}

}
