package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ElementDataId generated by hbm2java
 */
public class ElementDataId implements java.io.Serializable {

	private BigDecimal valId;
	private BigDecimal elementIdLink;
	private BigDecimal valParentId;
	private String valV;
	private Date valDBeg;
	private Date valDEnd;
	private Date valD;
	private BigDecimal valN;
	private BigDecimal elementParentIdLink;

	public ElementDataId() {
	}

	public ElementDataId(BigDecimal elementIdLink) {
		this.elementIdLink = elementIdLink;
	}

	public ElementDataId(BigDecimal valId, BigDecimal elementIdLink,
			BigDecimal valParentId, String valV, Date valDBeg, Date valDEnd,
			Date valD, BigDecimal valN, BigDecimal elementParentIdLink) {
		this.valId = valId;
		this.elementIdLink = elementIdLink;
		this.valParentId = valParentId;
		this.valV = valV;
		this.valDBeg = valDBeg;
		this.valDEnd = valDEnd;
		this.valD = valD;
		this.valN = valN;
		this.elementParentIdLink = elementParentIdLink;
	}

	public BigDecimal getValId() {
		return this.valId;
	}

	public void setValId(BigDecimal valId) {
		this.valId = valId;
	}

	public BigDecimal getElementIdLink() {
		return this.elementIdLink;
	}

	public void setElementIdLink(BigDecimal elementIdLink) {
		this.elementIdLink = elementIdLink;
	}

	public BigDecimal getValParentId() {
		return this.valParentId;
	}

	public void setValParentId(BigDecimal valParentId) {
		this.valParentId = valParentId;
	}

	public String getValV() {
		return this.valV;
	}

	public void setValV(String valV) {
		this.valV = valV;
	}

	public Date getValDBeg() {
		return this.valDBeg;
	}

	public void setValDBeg(Date valDBeg) {
		this.valDBeg = valDBeg;
	}

	public Date getValDEnd() {
		return this.valDEnd;
	}

	public void setValDEnd(Date valDEnd) {
		this.valDEnd = valDEnd;
	}

	public Date getValD() {
		return this.valD;
	}

	public void setValD(Date valD) {
		this.valD = valD;
	}

	public BigDecimal getValN() {
		return this.valN;
	}

	public void setValN(BigDecimal valN) {
		this.valN = valN;
	}

	public BigDecimal getElementParentIdLink() {
		return this.elementParentIdLink;
	}

	public void setElementParentIdLink(BigDecimal elementParentIdLink) {
		this.elementParentIdLink = elementParentIdLink;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElementDataId))
			return false;
		ElementDataId castOther = (ElementDataId) other;

		return ((this.getValId() == castOther.getValId()) || (this.getValId() != null
				&& castOther.getValId() != null && this.getValId().equals(
				castOther.getValId())))
				&& ((this.getElementIdLink() == castOther.getElementIdLink()) || (this
						.getElementIdLink() != null
						&& castOther.getElementIdLink() != null && this
						.getElementIdLink()
						.equals(castOther.getElementIdLink())))
				&& ((this.getValParentId() == castOther.getValParentId()) || (this
						.getValParentId() != null
						&& castOther.getValParentId() != null && this
						.getValParentId().equals(castOther.getValParentId())))
				&& ((this.getValV() == castOther.getValV()) || (this.getValV() != null
						&& castOther.getValV() != null && this.getValV()
						.equals(castOther.getValV())))
				&& ((this.getValDBeg() == castOther.getValDBeg()) || (this
						.getValDBeg() != null && castOther.getValDBeg() != null && this
						.getValDBeg().equals(castOther.getValDBeg())))
				&& ((this.getValDEnd() == castOther.getValDEnd()) || (this
						.getValDEnd() != null && castOther.getValDEnd() != null && this
						.getValDEnd().equals(castOther.getValDEnd())))
				&& ((this.getValD() == castOther.getValD()) || (this.getValD() != null
						&& castOther.getValD() != null && this.getValD()
						.equals(castOther.getValD())))
				&& ((this.getValN() == castOther.getValN()) || (this.getValN() != null
						&& castOther.getValN() != null && this.getValN()
						.equals(castOther.getValN())))
				&& ((this.getElementParentIdLink() == castOther
						.getElementParentIdLink()) || (this
						.getElementParentIdLink() != null
						&& castOther.getElementParentIdLink() != null && this
						.getElementParentIdLink().equals(
								castOther.getElementParentIdLink())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getValId() == null ? 0 : this.getValId().hashCode());
		result = 37
				* result
				+ (getElementIdLink() == null ? 0 : this.getElementIdLink()
						.hashCode());
		result = 37
				* result
				+ (getValParentId() == null ? 0 : this.getValParentId()
						.hashCode());
		result = 37 * result
				+ (getValV() == null ? 0 : this.getValV().hashCode());
		result = 37 * result
				+ (getValDBeg() == null ? 0 : this.getValDBeg().hashCode());
		result = 37 * result
				+ (getValDEnd() == null ? 0 : this.getValDEnd().hashCode());
		result = 37 * result
				+ (getValD() == null ? 0 : this.getValD().hashCode());
		result = 37 * result
				+ (getValN() == null ? 0 : this.getValN().hashCode());
		result = 37
				* result
				+ (getElementParentIdLink() == null ? 0 : this
						.getElementParentIdLink().hashCode());
		return result;
	}

}
