package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Elements generated by hbm2java
 */
public class Elements implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal ptrId;
	private String name;
	private BigDecimal parentId;
	private String cd;
	private BigDecimal treeId;
	private String ordCd;

	public Elements() {
	}

	public Elements(BigDecimal id) {
		this.id = id;
	}

	public Elements(BigDecimal id, BigDecimal ptrId, String name,
			BigDecimal parentId, String cd, BigDecimal treeId, String ordCd) {
		this.id = id;
		this.ptrId = ptrId;
		this.name = name;
		this.parentId = parentId;
		this.cd = cd;
		this.treeId = treeId;
		this.ordCd = ordCd;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getPtrId() {
		return this.ptrId;
	}

	public void setPtrId(BigDecimal ptrId) {
		this.ptrId = ptrId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getParentId() {
		return this.parentId;
	}

	public void setParentId(BigDecimal parentId) {
		this.parentId = parentId;
	}

	public String getCd() {
		return this.cd;
	}

	public void setCd(String cd) {
		this.cd = cd;
	}

	public BigDecimal getTreeId() {
		return this.treeId;
	}

	public void setTreeId(BigDecimal treeId) {
		this.treeId = treeId;
	}

	public String getOrdCd() {
		return this.ordCd;
	}

	public void setOrdCd(String ordCd) {
		this.ordCd = ordCd;
	}

}
