package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * ElementData generated by hbm2java
 */
public class ElementData implements java.io.Serializable {

	private ElementDataId id;

	public ElementData() {
	}

	public ElementData(ElementDataId id) {
		this.id = id;
	}

	public ElementDataId getId() {
		return this.id;
	}

	public void setId(ElementDataId id) {
		this.id = id;
	}

}
