package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * ElementDataBlob generated by hbm2java
 */
public class ElementDataBlob implements java.io.Serializable {

	private ElementDataBlobId id;

	public ElementDataBlob() {
	}

	public ElementDataBlob(ElementDataBlobId id) {
		this.id = id;
	}

	public ElementDataBlobId getId() {
		return this.id;
	}

	public void setId(ElementDataBlobId id) {
		this.id = id;
	}

}
