package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * Faces generated by hbm2java
 */
public class Faces implements java.io.Serializable {

	private FacesId id;

	public Faces() {
	}

	public Faces(FacesId id) {
		this.id = id;
	}

	public FacesId getId() {
		return this.id;
	}

	public void setId(FacesId id) {
		this.id = id;
	}

}
