package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * FiasHouse42 generated by hbm2java
 */
public class FiasHouse42 implements java.io.Serializable {

	private FiasHouse42Id id;

	public FiasHouse42() {
	}

	public FiasHouse42(FiasHouse42Id id) {
		this.id = id;
	}

	public FiasHouse42Id getId() {
		return this.id;
	}

	public void setId(FiasHouse42Id id) {
		this.id = id;
	}

}
