package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * FiasAddrobj generated by hbm2java
 */
public class FiasAddrobj implements java.io.Serializable {

	private FiasAddrobjId id;

	public FiasAddrobj() {
	}

	public FiasAddrobj(FiasAddrobjId id) {
		this.id = id;
	}

	public FiasAddrobjId getId() {
		return this.id;
	}

	public void setId(FiasAddrobjId id) {
		this.id = id;
	}

}
