package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FiasHouse42Id generated by hbm2java
 */
public class FiasHouse42Id implements java.io.Serializable {

	private String aoguid;
	private String buildnum;
	private Date enddate;
	private Double eststatus;
	private String houseguid;
	private String houseid;
	private String housenum;
	private Double statstatus;
	private String ifnsfl;
	private String ifnsul;
	private String okato;
	private String oktmo;
	private String postalcode;
	private Date startdate;
	private String strucnum;
	private Double strstatus;
	private String terrifnsfl;
	private String terrifnsul;
	private Date updatedate;
	private String normdoc;
	private Double counter;

	public FiasHouse42Id() {
	}

	public FiasHouse42Id(String aoguid, String buildnum, Date enddate,
			Double eststatus, String houseguid, String houseid,
			String housenum, Double statstatus, String ifnsfl, String ifnsul,
			String okato, String oktmo, String postalcode, Date startdate,
			String strucnum, Double strstatus, String terrifnsfl,
			String terrifnsul, Date updatedate, String normdoc, Double counter) {
		this.aoguid = aoguid;
		this.buildnum = buildnum;
		this.enddate = enddate;
		this.eststatus = eststatus;
		this.houseguid = houseguid;
		this.houseid = houseid;
		this.housenum = housenum;
		this.statstatus = statstatus;
		this.ifnsfl = ifnsfl;
		this.ifnsul = ifnsul;
		this.okato = okato;
		this.oktmo = oktmo;
		this.postalcode = postalcode;
		this.startdate = startdate;
		this.strucnum = strucnum;
		this.strstatus = strstatus;
		this.terrifnsfl = terrifnsfl;
		this.terrifnsul = terrifnsul;
		this.updatedate = updatedate;
		this.normdoc = normdoc;
		this.counter = counter;
	}

	public String getAoguid() {
		return this.aoguid;
	}

	public void setAoguid(String aoguid) {
		this.aoguid = aoguid;
	}

	public String getBuildnum() {
		return this.buildnum;
	}

	public void setBuildnum(String buildnum) {
		this.buildnum = buildnum;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public Double getEststatus() {
		return this.eststatus;
	}

	public void setEststatus(Double eststatus) {
		this.eststatus = eststatus;
	}

	public String getHouseguid() {
		return this.houseguid;
	}

	public void setHouseguid(String houseguid) {
		this.houseguid = houseguid;
	}

	public String getHouseid() {
		return this.houseid;
	}

	public void setHouseid(String houseid) {
		this.houseid = houseid;
	}

	public String getHousenum() {
		return this.housenum;
	}

	public void setHousenum(String housenum) {
		this.housenum = housenum;
	}

	public Double getStatstatus() {
		return this.statstatus;
	}

	public void setStatstatus(Double statstatus) {
		this.statstatus = statstatus;
	}

	public String getIfnsfl() {
		return this.ifnsfl;
	}

	public void setIfnsfl(String ifnsfl) {
		this.ifnsfl = ifnsfl;
	}

	public String getIfnsul() {
		return this.ifnsul;
	}

	public void setIfnsul(String ifnsul) {
		this.ifnsul = ifnsul;
	}

	public String getOkato() {
		return this.okato;
	}

	public void setOkato(String okato) {
		this.okato = okato;
	}

	public String getOktmo() {
		return this.oktmo;
	}

	public void setOktmo(String oktmo) {
		this.oktmo = oktmo;
	}

	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public String getStrucnum() {
		return this.strucnum;
	}

	public void setStrucnum(String strucnum) {
		this.strucnum = strucnum;
	}

	public Double getStrstatus() {
		return this.strstatus;
	}

	public void setStrstatus(Double strstatus) {
		this.strstatus = strstatus;
	}

	public String getTerrifnsfl() {
		return this.terrifnsfl;
	}

	public void setTerrifnsfl(String terrifnsfl) {
		this.terrifnsfl = terrifnsfl;
	}

	public String getTerrifnsul() {
		return this.terrifnsul;
	}

	public void setTerrifnsul(String terrifnsul) {
		this.terrifnsul = terrifnsul;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public String getNormdoc() {
		return this.normdoc;
	}

	public void setNormdoc(String normdoc) {
		this.normdoc = normdoc;
	}

	public Double getCounter() {
		return this.counter;
	}

	public void setCounter(Double counter) {
		this.counter = counter;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FiasHouse42Id))
			return false;
		FiasHouse42Id castOther = (FiasHouse42Id) other;

		return ((this.getAoguid() == castOther.getAoguid()) || (this
				.getAoguid() != null && castOther.getAoguid() != null && this
				.getAoguid().equals(castOther.getAoguid())))
				&& ((this.getBuildnum() == castOther.getBuildnum()) || (this
						.getBuildnum() != null
						&& castOther.getBuildnum() != null && this
						.getBuildnum().equals(castOther.getBuildnum())))
				&& ((this.getEnddate() == castOther.getEnddate()) || (this
						.getEnddate() != null && castOther.getEnddate() != null && this
						.getEnddate().equals(castOther.getEnddate())))
				&& ((this.getEststatus() == castOther.getEststatus()) || (this
						.getEststatus() != null
						&& castOther.getEststatus() != null && this
						.getEststatus().equals(castOther.getEststatus())))
				&& ((this.getHouseguid() == castOther.getHouseguid()) || (this
						.getHouseguid() != null
						&& castOther.getHouseguid() != null && this
						.getHouseguid().equals(castOther.getHouseguid())))
				&& ((this.getHouseid() == castOther.getHouseid()) || (this
						.getHouseid() != null && castOther.getHouseid() != null && this
						.getHouseid().equals(castOther.getHouseid())))
				&& ((this.getHousenum() == castOther.getHousenum()) || (this
						.getHousenum() != null
						&& castOther.getHousenum() != null && this
						.getHousenum().equals(castOther.getHousenum())))
				&& ((this.getStatstatus() == castOther.getStatstatus()) || (this
						.getStatstatus() != null
						&& castOther.getStatstatus() != null && this
						.getStatstatus().equals(castOther.getStatstatus())))
				&& ((this.getIfnsfl() == castOther.getIfnsfl()) || (this
						.getIfnsfl() != null && castOther.getIfnsfl() != null && this
						.getIfnsfl().equals(castOther.getIfnsfl())))
				&& ((this.getIfnsul() == castOther.getIfnsul()) || (this
						.getIfnsul() != null && castOther.getIfnsul() != null && this
						.getIfnsul().equals(castOther.getIfnsul())))
				&& ((this.getOkato() == castOther.getOkato()) || (this
						.getOkato() != null && castOther.getOkato() != null && this
						.getOkato().equals(castOther.getOkato())))
				&& ((this.getOktmo() == castOther.getOktmo()) || (this
						.getOktmo() != null && castOther.getOktmo() != null && this
						.getOktmo().equals(castOther.getOktmo())))
				&& ((this.getPostalcode() == castOther.getPostalcode()) || (this
						.getPostalcode() != null
						&& castOther.getPostalcode() != null && this
						.getPostalcode().equals(castOther.getPostalcode())))
				&& ((this.getStartdate() == castOther.getStartdate()) || (this
						.getStartdate() != null
						&& castOther.getStartdate() != null && this
						.getStartdate().equals(castOther.getStartdate())))
				&& ((this.getStrucnum() == castOther.getStrucnum()) || (this
						.getStrucnum() != null
						&& castOther.getStrucnum() != null && this
						.getStrucnum().equals(castOther.getStrucnum())))
				&& ((this.getStrstatus() == castOther.getStrstatus()) || (this
						.getStrstatus() != null
						&& castOther.getStrstatus() != null && this
						.getStrstatus().equals(castOther.getStrstatus())))
				&& ((this.getTerrifnsfl() == castOther.getTerrifnsfl()) || (this
						.getTerrifnsfl() != null
						&& castOther.getTerrifnsfl() != null && this
						.getTerrifnsfl().equals(castOther.getTerrifnsfl())))
				&& ((this.getTerrifnsul() == castOther.getTerrifnsul()) || (this
						.getTerrifnsul() != null
						&& castOther.getTerrifnsul() != null && this
						.getTerrifnsul().equals(castOther.getTerrifnsul())))
				&& ((this.getUpdatedate() == castOther.getUpdatedate()) || (this
						.getUpdatedate() != null
						&& castOther.getUpdatedate() != null && this
						.getUpdatedate().equals(castOther.getUpdatedate())))
				&& ((this.getNormdoc() == castOther.getNormdoc()) || (this
						.getNormdoc() != null && castOther.getNormdoc() != null && this
						.getNormdoc().equals(castOther.getNormdoc())))
				&& ((this.getCounter() == castOther.getCounter()) || (this
						.getCounter() != null && castOther.getCounter() != null && this
						.getCounter().equals(castOther.getCounter())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAoguid() == null ? 0 : this.getAoguid().hashCode());
		result = 37 * result
				+ (getBuildnum() == null ? 0 : this.getBuildnum().hashCode());
		result = 37 * result
				+ (getEnddate() == null ? 0 : this.getEnddate().hashCode());
		result = 37 * result
				+ (getEststatus() == null ? 0 : this.getEststatus().hashCode());
		result = 37 * result
				+ (getHouseguid() == null ? 0 : this.getHouseguid().hashCode());
		result = 37 * result
				+ (getHouseid() == null ? 0 : this.getHouseid().hashCode());
		result = 37 * result
				+ (getHousenum() == null ? 0 : this.getHousenum().hashCode());
		result = 37
				* result
				+ (getStatstatus() == null ? 0 : this.getStatstatus()
						.hashCode());
		result = 37 * result
				+ (getIfnsfl() == null ? 0 : this.getIfnsfl().hashCode());
		result = 37 * result
				+ (getIfnsul() == null ? 0 : this.getIfnsul().hashCode());
		result = 37 * result
				+ (getOkato() == null ? 0 : this.getOkato().hashCode());
		result = 37 * result
				+ (getOktmo() == null ? 0 : this.getOktmo().hashCode());
		result = 37
				* result
				+ (getPostalcode() == null ? 0 : this.getPostalcode()
						.hashCode());
		result = 37 * result
				+ (getStartdate() == null ? 0 : this.getStartdate().hashCode());
		result = 37 * result
				+ (getStrucnum() == null ? 0 : this.getStrucnum().hashCode());
		result = 37 * result
				+ (getStrstatus() == null ? 0 : this.getStrstatus().hashCode());
		result = 37
				* result
				+ (getTerrifnsfl() == null ? 0 : this.getTerrifnsfl()
						.hashCode());
		result = 37
				* result
				+ (getTerrifnsul() == null ? 0 : this.getTerrifnsul()
						.hashCode());
		result = 37
				* result
				+ (getUpdatedate() == null ? 0 : this.getUpdatedate()
						.hashCode());
		result = 37 * result
				+ (getNormdoc() == null ? 0 : this.getNormdoc().hashCode());
		result = 37 * result
				+ (getCounter() == null ? 0 : this.getCounter().hashCode());
		return result;
	}

}
