package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;

/**
 * GisTemplateId generated by hbm2java
 */
public class GisTemplateId implements java.io.Serializable {

	private BigDecimal id;
	private Blob template;
	private String comm;
	private BigDecimal cntPg;
	private Boolean forImp;
	private Boolean forExp;
	private String templImp;

	public GisTemplateId() {
	}

	public GisTemplateId(BigDecimal id) {
		this.id = id;
	}

	public GisTemplateId(BigDecimal id, Blob template, String comm,
			BigDecimal cntPg, Boolean forImp, Boolean forExp, String templImp) {
		this.id = id;
		this.template = template;
		this.comm = comm;
		this.cntPg = cntPg;
		this.forImp = forImp;
		this.forExp = forExp;
		this.templImp = templImp;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Blob getTemplate() {
		return this.template;
	}

	public void setTemplate(Blob template) {
		this.template = template;
	}

	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

	public BigDecimal getCntPg() {
		return this.cntPg;
	}

	public void setCntPg(BigDecimal cntPg) {
		this.cntPg = cntPg;
	}

	public Boolean getForImp() {
		return this.forImp;
	}

	public void setForImp(Boolean forImp) {
		this.forImp = forImp;
	}

	public Boolean getForExp() {
		return this.forExp;
	}

	public void setForExp(Boolean forExp) {
		this.forExp = forExp;
	}

	public String getTemplImp() {
		return this.templImp;
	}

	public void setTemplImp(String templImp) {
		this.templImp = templImp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GisTemplateId))
			return false;
		GisTemplateId castOther = (GisTemplateId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getTemplate() == castOther.getTemplate()) || (this
						.getTemplate() != null
						&& castOther.getTemplate() != null && this
						.getTemplate().equals(castOther.getTemplate())))
				&& ((this.getComm() == castOther.getComm()) || (this.getComm() != null
						&& castOther.getComm() != null && this.getComm()
						.equals(castOther.getComm())))
				&& ((this.getCntPg() == castOther.getCntPg()) || (this
						.getCntPg() != null && castOther.getCntPg() != null && this
						.getCntPg().equals(castOther.getCntPg())))
				&& ((this.getForImp() == castOther.getForImp()) || (this
						.getForImp() != null && castOther.getForImp() != null && this
						.getForImp().equals(castOther.getForImp())))
				&& ((this.getForExp() == castOther.getForExp()) || (this
						.getForExp() != null && castOther.getForExp() != null && this
						.getForExp().equals(castOther.getForExp())))
				&& ((this.getTemplImp() == castOther.getTemplImp()) || (this
						.getTemplImp() != null
						&& castOther.getTemplImp() != null && this
						.getTemplImp().equals(castOther.getTemplImp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getTemplate() == null ? 0 : this.getTemplate().hashCode());
		result = 37 * result
				+ (getComm() == null ? 0 : this.getComm().hashCode());
		result = 37 * result
				+ (getCntPg() == null ? 0 : this.getCntPg().hashCode());
		result = 37 * result
				+ (getForImp() == null ? 0 : this.getForImp().hashCode());
		result = 37 * result
				+ (getForExp() == null ? 0 : this.getForExp().hashCode());
		result = 37 * result
				+ (getTemplImp() == null ? 0 : this.getTemplImp().hashCode());
		return result;
	}

}
