package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * GisTemplate generated by hbm2java
 */
public class GisTemplate implements java.io.Serializable {

	private GisTemplateId id;

	public GisTemplate() {
	}

	public GisTemplate(GisTemplateId id) {
		this.id = id;
	}

	public GisTemplateId getId() {
		return this.id;
	}

	public void setId(GisTemplateId id) {
		this.id = id;
	}

}
