package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * HistoryLsk generated by hbm2java
 */
public class HistoryLsk implements java.io.Serializable {

	private HistoryLskId id;

	public HistoryLsk() {
	}

	public HistoryLsk(HistoryLskId id) {
		this.id = id;
	}

	public HistoryLskId getId() {
		return this.id;
	}

	public void setId(HistoryLskId id) {
		this.id = id;
	}

}
