package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * HistoryLskId generated by hbm2java
 */
public class HistoryLskId implements java.io.Serializable {

	private String lsk;
	private String kul;
	private String nd;
	private String kw;
	private String fio;
	private String reu;
	private Byte status;
	private Long CLskId;
	private Long houseId;
	private Boolean psch;
	private String mg1;
	private String mg2;
	private String lskNew;

	public HistoryLskId() {
	}

	public HistoryLskId(String lsk, String kul, String nd, String kw,
			String fio, String reu, Byte status, Long CLskId, Long houseId,
			Boolean psch, String mg1, String mg2, String lskNew) {
		this.lsk = lsk;
		this.kul = kul;
		this.nd = nd;
		this.kw = kw;
		this.fio = fio;
		this.reu = reu;
		this.status = status;
		this.CLskId = CLskId;
		this.houseId = houseId;
		this.psch = psch;
		this.mg1 = mg1;
		this.mg2 = mg2;
		this.lskNew = lskNew;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public String getKul() {
		return this.kul;
	}

	public void setKul(String kul) {
		this.kul = kul;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getKw() {
		return this.kw;
	}

	public void setKw(String kw) {
		this.kw = kw;
	}

	public String getFio() {
		return this.fio;
	}

	public void setFio(String fio) {
		this.fio = fio;
	}

	public String getReu() {
		return this.reu;
	}

	public void setReu(String reu) {
		this.reu = reu;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Long getCLskId() {
		return this.CLskId;
	}

	public void setCLskId(Long CLskId) {
		this.CLskId = CLskId;
	}

	public Long getHouseId() {
		return this.houseId;
	}

	public void setHouseId(Long houseId) {
		this.houseId = houseId;
	}

	public Boolean getPsch() {
		return this.psch;
	}

	public void setPsch(Boolean psch) {
		this.psch = psch;
	}

	public String getMg1() {
		return this.mg1;
	}

	public void setMg1(String mg1) {
		this.mg1 = mg1;
	}

	public String getMg2() {
		return this.mg2;
	}

	public void setMg2(String mg2) {
		this.mg2 = mg2;
	}

	public String getLskNew() {
		return this.lskNew;
	}

	public void setLskNew(String lskNew) {
		this.lskNew = lskNew;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoryLskId))
			return false;
		HistoryLskId castOther = (HistoryLskId) other;

		return ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
				&& castOther.getLsk() != null && this.getLsk().equals(
				castOther.getLsk())))
				&& ((this.getKul() == castOther.getKul()) || (this.getKul() != null
						&& castOther.getKul() != null && this.getKul().equals(
						castOther.getKul())))
				&& ((this.getNd() == castOther.getNd()) || (this.getNd() != null
						&& castOther.getNd() != null && this.getNd().equals(
						castOther.getNd())))
				&& ((this.getKw() == castOther.getKw()) || (this.getKw() != null
						&& castOther.getKw() != null && this.getKw().equals(
						castOther.getKw())))
				&& ((this.getFio() == castOther.getFio()) || (this.getFio() != null
						&& castOther.getFio() != null && this.getFio().equals(
						castOther.getFio())))
				&& ((this.getReu() == castOther.getReu()) || (this.getReu() != null
						&& castOther.getReu() != null && this.getReu().equals(
						castOther.getReu())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getCLskId() == castOther.getCLskId()) || (this
						.getCLskId() != null && castOther.getCLskId() != null && this
						.getCLskId().equals(castOther.getCLskId())))
				&& ((this.getHouseId() == castOther.getHouseId()) || (this
						.getHouseId() != null && castOther.getHouseId() != null && this
						.getHouseId().equals(castOther.getHouseId())))
				&& ((this.getPsch() == castOther.getPsch()) || (this.getPsch() != null
						&& castOther.getPsch() != null && this.getPsch()
						.equals(castOther.getPsch())))
				&& ((this.getMg1() == castOther.getMg1()) || (this.getMg1() != null
						&& castOther.getMg1() != null && this.getMg1().equals(
						castOther.getMg1())))
				&& ((this.getMg2() == castOther.getMg2()) || (this.getMg2() != null
						&& castOther.getMg2() != null && this.getMg2().equals(
						castOther.getMg2())))
				&& ((this.getLskNew() == castOther.getLskNew()) || (this
						.getLskNew() != null && castOther.getLskNew() != null && this
						.getLskNew().equals(castOther.getLskNew())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getKul() == null ? 0 : this.getKul().hashCode());
		result = 37 * result + (getNd() == null ? 0 : this.getNd().hashCode());
		result = 37 * result + (getKw() == null ? 0 : this.getKw().hashCode());
		result = 37 * result
				+ (getFio() == null ? 0 : this.getFio().hashCode());
		result = 37 * result
				+ (getReu() == null ? 0 : this.getReu().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getCLskId() == null ? 0 : this.getCLskId().hashCode());
		result = 37 * result
				+ (getHouseId() == null ? 0 : this.getHouseId().hashCode());
		result = 37 * result
				+ (getPsch() == null ? 0 : this.getPsch().hashCode());
		result = 37 * result
				+ (getMg1() == null ? 0 : this.getMg1().hashCode());
		result = 37 * result
				+ (getMg2() == null ? 0 : this.getMg2().hashCode());
		result = 37 * result
				+ (getLskNew() == null ? 0 : this.getLskNew().hashCode());
		return result;
	}

}
