package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * HousesGuid generated by hbm2java
 */
public class HousesGuid implements java.io.Serializable {

	private HousesGuidId id;

	public HousesGuid() {
	}

	public HousesGuid(HousesGuidId id) {
		this.id = id;
	}

	public HousesGuidId getId() {
		return this.id;
	}

	public void setId(HousesGuidId id) {
		this.id = id;
	}

}
