package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * HousesGuidId generated by hbm2java
 */
public class HousesGuidId implements java.io.Serializable {

	private String kul;
	private String nd;
	private String reu;
	private String houseguid;
	private String adr;
	private String uhouseCd;
	private String oktmo;
	private String gkn;

	public HousesGuidId() {
	}

	public HousesGuidId(String kul, String nd, String reu, String houseguid,
			String adr, String uhouseCd, String oktmo, String gkn) {
		this.kul = kul;
		this.nd = nd;
		this.reu = reu;
		this.houseguid = houseguid;
		this.adr = adr;
		this.uhouseCd = uhouseCd;
		this.oktmo = oktmo;
		this.gkn = gkn;
	}

	public String getKul() {
		return this.kul;
	}

	public void setKul(String kul) {
		this.kul = kul;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getReu() {
		return this.reu;
	}

	public void setReu(String reu) {
		this.reu = reu;
	}

	public String getHouseguid() {
		return this.houseguid;
	}

	public void setHouseguid(String houseguid) {
		this.houseguid = houseguid;
	}

	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	public String getUhouseCd() {
		return this.uhouseCd;
	}

	public void setUhouseCd(String uhouseCd) {
		this.uhouseCd = uhouseCd;
	}

	public String getOktmo() {
		return this.oktmo;
	}

	public void setOktmo(String oktmo) {
		this.oktmo = oktmo;
	}

	public String getGkn() {
		return this.gkn;
	}

	public void setGkn(String gkn) {
		this.gkn = gkn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HousesGuidId))
			return false;
		HousesGuidId castOther = (HousesGuidId) other;

		return ((this.getKul() == castOther.getKul()) || (this.getKul() != null
				&& castOther.getKul() != null && this.getKul().equals(
				castOther.getKul())))
				&& ((this.getNd() == castOther.getNd()) || (this.getNd() != null
						&& castOther.getNd() != null && this.getNd().equals(
						castOther.getNd())))
				&& ((this.getReu() == castOther.getReu()) || (this.getReu() != null
						&& castOther.getReu() != null && this.getReu().equals(
						castOther.getReu())))
				&& ((this.getHouseguid() == castOther.getHouseguid()) || (this
						.getHouseguid() != null
						&& castOther.getHouseguid() != null && this
						.getHouseguid().equals(castOther.getHouseguid())))
				&& ((this.getAdr() == castOther.getAdr()) || (this.getAdr() != null
						&& castOther.getAdr() != null && this.getAdr().equals(
						castOther.getAdr())))
				&& ((this.getUhouseCd() == castOther.getUhouseCd()) || (this
						.getUhouseCd() != null
						&& castOther.getUhouseCd() != null && this
						.getUhouseCd().equals(castOther.getUhouseCd())))
				&& ((this.getOktmo() == castOther.getOktmo()) || (this
						.getOktmo() != null && castOther.getOktmo() != null && this
						.getOktmo().equals(castOther.getOktmo())))
				&& ((this.getGkn() == castOther.getGkn()) || (this.getGkn() != null
						&& castOther.getGkn() != null && this.getGkn().equals(
						castOther.getGkn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKul() == null ? 0 : this.getKul().hashCode());
		result = 37 * result + (getNd() == null ? 0 : this.getNd().hashCode());
		result = 37 * result
				+ (getReu() == null ? 0 : this.getReu().hashCode());
		result = 37 * result
				+ (getHouseguid() == null ? 0 : this.getHouseguid().hashCode());
		result = 37 * result
				+ (getAdr() == null ? 0 : this.getAdr().hashCode());
		result = 37 * result
				+ (getUhouseCd() == null ? 0 : this.getUhouseCd().hashCode());
		result = 37 * result
				+ (getOktmo() == null ? 0 : this.getOktmo().hashCode());
		result = 37 * result
				+ (getGkn() == null ? 0 : this.getGkn().hashCode());
		return result;
	}

}
