package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * KwniId generated by hbm2java
 */
public class KwniId implements java.io.Serializable {

	private String lsk;
	private Double ikr;
	private Double ikri;
	private Double itr;
	private Double itri;
	private Double ider;
	private Double ideri;
	private Double ot;
	private Double iot;
	private Double iotip;
	private Double iottr;
	private Double iottri;
	private Double hw;
	private Double iwod;
	private Double iwodiz;
	private Double iwodtr;
	private Double iwodtri;
	private Double hwDop;
	private Double idophw;
	private Double idopht;
	private Double gw;
	private Double igw;
	private Double igwiz;
	private Double igwtr;
	private Double igwtri;
	private Double gwDop;
	private Double idopgw;
	private Double idopgt;
	private Double io;
	private Double ioi;
	private Double ian;
	private Double ianD;
	private Double ir;
	private Double ig;
	private Double igi;
	private Double igtr;
	private Double igtri;
	private Double ios;
	private Double kwt;
	private Double iosKarm;
	private Double kwtDop;
	private Double i101;
	private Double ics;
	private Double iao;
	private Double ikz;
	private Double ier;
	private Double ikan;
	private Double ikaniz;
	private Double idopkan;
	private Double imusor;
	private Double imusi;
	private Double ilif;
	private Double ilifi;
	private Double imPr;
	private Double impri;
	private Double idtPl;
	private Double ikzm;
	private Double ielpl;
	private Double irezerv;
	private Double ikPli;
	private Double iplel;
	private Double ivaxt;
	private Double ivaxti;
	private Double i45;
	private Double i46;
	private Double i47;
	private Double i48;
	private Double iknai;
	private Double iland;
	private Double i49;
	private Double i50;
	private Double i51;
	private Double i52;
	private Double i53;
	private Double i54;
	private Double i55;
	private Double i56;
	private Double i57;
	private Double i58;
	private Double i59;
	private Double i60;
	private Double i61;
	private Double hw344;
	private Double hw344d;
	private Double ihw344;
	private Double ihw344d;
	private Double gw344;
	private Double gw344d;
	private Double igw344;
	private Double igw344d;
	private Double el344;
	private Double el344d;
	private Double iel344;
	private Double iel344d;
	private Double ot344d;
	private Double iot344d;
	private String dtizm;
	private String schI;
	private Date dtek;
	private String nkom;
	private String prim;
	private String lp;
	private Double type;
	private BigDecimal i62;
	private BigDecimal i63;
	private BigDecimal i64;
	private BigDecimal i65;
	private BigDecimal i66;
	private BigDecimal i67;
	private BigDecimal i68;
	private BigDecimal i69;
	private BigDecimal i70;

	public KwniId() {
	}

	public KwniId(String lsk, Double ikr, Double ikri, Double itr, Double itri,
			Double ider, Double ideri, Double ot, Double iot, Double iotip,
			Double iottr, Double iottri, Double hw, Double iwod, Double iwodiz,
			Double iwodtr, Double iwodtri, Double hwDop, Double idophw,
			Double idopht, Double gw, Double igw, Double igwiz, Double igwtr,
			Double igwtri, Double gwDop, Double idopgw, Double idopgt,
			Double io, Double ioi, Double ian, Double ianD, Double ir,
			Double ig, Double igi, Double igtr, Double igtri, Double ios,
			Double kwt, Double iosKarm, Double kwtDop, Double i101, Double ics,
			Double iao, Double ikz, Double ier, Double ikan, Double ikaniz,
			Double idopkan, Double imusor, Double imusi, Double ilif,
			Double ilifi, Double imPr, Double impri, Double idtPl, Double ikzm,
			Double ielpl, Double irezerv, Double ikPli, Double iplel,
			Double ivaxt, Double ivaxti, Double i45, Double i46, Double i47,
			Double i48, Double iknai, Double iland, Double i49, Double i50,
			Double i51, Double i52, Double i53, Double i54, Double i55,
			Double i56, Double i57, Double i58, Double i59, Double i60,
			Double i61, Double hw344, Double hw344d, Double ihw344,
			Double ihw344d, Double gw344, Double gw344d, Double igw344,
			Double igw344d, Double el344, Double el344d, Double iel344,
			Double iel344d, Double ot344d, Double iot344d, String dtizm,
			String schI, Date dtek, String nkom, String prim, String lp,
			Double type, BigDecimal i62, BigDecimal i63, BigDecimal i64,
			BigDecimal i65, BigDecimal i66, BigDecimal i67, BigDecimal i68,
			BigDecimal i69, BigDecimal i70) {
		this.lsk = lsk;
		this.ikr = ikr;
		this.ikri = ikri;
		this.itr = itr;
		this.itri = itri;
		this.ider = ider;
		this.ideri = ideri;
		this.ot = ot;
		this.iot = iot;
		this.iotip = iotip;
		this.iottr = iottr;
		this.iottri = iottri;
		this.hw = hw;
		this.iwod = iwod;
		this.iwodiz = iwodiz;
		this.iwodtr = iwodtr;
		this.iwodtri = iwodtri;
		this.hwDop = hwDop;
		this.idophw = idophw;
		this.idopht = idopht;
		this.gw = gw;
		this.igw = igw;
		this.igwiz = igwiz;
		this.igwtr = igwtr;
		this.igwtri = igwtri;
		this.gwDop = gwDop;
		this.idopgw = idopgw;
		this.idopgt = idopgt;
		this.io = io;
		this.ioi = ioi;
		this.ian = ian;
		this.ianD = ianD;
		this.ir = ir;
		this.ig = ig;
		this.igi = igi;
		this.igtr = igtr;
		this.igtri = igtri;
		this.ios = ios;
		this.kwt = kwt;
		this.iosKarm = iosKarm;
		this.kwtDop = kwtDop;
		this.i101 = i101;
		this.ics = ics;
		this.iao = iao;
		this.ikz = ikz;
		this.ier = ier;
		this.ikan = ikan;
		this.ikaniz = ikaniz;
		this.idopkan = idopkan;
		this.imusor = imusor;
		this.imusi = imusi;
		this.ilif = ilif;
		this.ilifi = ilifi;
		this.imPr = imPr;
		this.impri = impri;
		this.idtPl = idtPl;
		this.ikzm = ikzm;
		this.ielpl = ielpl;
		this.irezerv = irezerv;
		this.ikPli = ikPli;
		this.iplel = iplel;
		this.ivaxt = ivaxt;
		this.ivaxti = ivaxti;
		this.i45 = i45;
		this.i46 = i46;
		this.i47 = i47;
		this.i48 = i48;
		this.iknai = iknai;
		this.iland = iland;
		this.i49 = i49;
		this.i50 = i50;
		this.i51 = i51;
		this.i52 = i52;
		this.i53 = i53;
		this.i54 = i54;
		this.i55 = i55;
		this.i56 = i56;
		this.i57 = i57;
		this.i58 = i58;
		this.i59 = i59;
		this.i60 = i60;
		this.i61 = i61;
		this.hw344 = hw344;
		this.hw344d = hw344d;
		this.ihw344 = ihw344;
		this.ihw344d = ihw344d;
		this.gw344 = gw344;
		this.gw344d = gw344d;
		this.igw344 = igw344;
		this.igw344d = igw344d;
		this.el344 = el344;
		this.el344d = el344d;
		this.iel344 = iel344;
		this.iel344d = iel344d;
		this.ot344d = ot344d;
		this.iot344d = iot344d;
		this.dtizm = dtizm;
		this.schI = schI;
		this.dtek = dtek;
		this.nkom = nkom;
		this.prim = prim;
		this.lp = lp;
		this.type = type;
		this.i62 = i62;
		this.i63 = i63;
		this.i64 = i64;
		this.i65 = i65;
		this.i66 = i66;
		this.i67 = i67;
		this.i68 = i68;
		this.i69 = i69;
		this.i70 = i70;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public Double getIkr() {
		return this.ikr;
	}

	public void setIkr(Double ikr) {
		this.ikr = ikr;
	}

	public Double getIkri() {
		return this.ikri;
	}

	public void setIkri(Double ikri) {
		this.ikri = ikri;
	}

	public Double getItr() {
		return this.itr;
	}

	public void setItr(Double itr) {
		this.itr = itr;
	}

	public Double getItri() {
		return this.itri;
	}

	public void setItri(Double itri) {
		this.itri = itri;
	}

	public Double getIder() {
		return this.ider;
	}

	public void setIder(Double ider) {
		this.ider = ider;
	}

	public Double getIderi() {
		return this.ideri;
	}

	public void setIderi(Double ideri) {
		this.ideri = ideri;
	}

	public Double getOt() {
		return this.ot;
	}

	public void setOt(Double ot) {
		this.ot = ot;
	}

	public Double getIot() {
		return this.iot;
	}

	public void setIot(Double iot) {
		this.iot = iot;
	}

	public Double getIotip() {
		return this.iotip;
	}

	public void setIotip(Double iotip) {
		this.iotip = iotip;
	}

	public Double getIottr() {
		return this.iottr;
	}

	public void setIottr(Double iottr) {
		this.iottr = iottr;
	}

	public Double getIottri() {
		return this.iottri;
	}

	public void setIottri(Double iottri) {
		this.iottri = iottri;
	}

	public Double getHw() {
		return this.hw;
	}

	public void setHw(Double hw) {
		this.hw = hw;
	}

	public Double getIwod() {
		return this.iwod;
	}

	public void setIwod(Double iwod) {
		this.iwod = iwod;
	}

	public Double getIwodiz() {
		return this.iwodiz;
	}

	public void setIwodiz(Double iwodiz) {
		this.iwodiz = iwodiz;
	}

	public Double getIwodtr() {
		return this.iwodtr;
	}

	public void setIwodtr(Double iwodtr) {
		this.iwodtr = iwodtr;
	}

	public Double getIwodtri() {
		return this.iwodtri;
	}

	public void setIwodtri(Double iwodtri) {
		this.iwodtri = iwodtri;
	}

	public Double getHwDop() {
		return this.hwDop;
	}

	public void setHwDop(Double hwDop) {
		this.hwDop = hwDop;
	}

	public Double getIdophw() {
		return this.idophw;
	}

	public void setIdophw(Double idophw) {
		this.idophw = idophw;
	}

	public Double getIdopht() {
		return this.idopht;
	}

	public void setIdopht(Double idopht) {
		this.idopht = idopht;
	}

	public Double getGw() {
		return this.gw;
	}

	public void setGw(Double gw) {
		this.gw = gw;
	}

	public Double getIgw() {
		return this.igw;
	}

	public void setIgw(Double igw) {
		this.igw = igw;
	}

	public Double getIgwiz() {
		return this.igwiz;
	}

	public void setIgwiz(Double igwiz) {
		this.igwiz = igwiz;
	}

	public Double getIgwtr() {
		return this.igwtr;
	}

	public void setIgwtr(Double igwtr) {
		this.igwtr = igwtr;
	}

	public Double getIgwtri() {
		return this.igwtri;
	}

	public void setIgwtri(Double igwtri) {
		this.igwtri = igwtri;
	}

	public Double getGwDop() {
		return this.gwDop;
	}

	public void setGwDop(Double gwDop) {
		this.gwDop = gwDop;
	}

	public Double getIdopgw() {
		return this.idopgw;
	}

	public void setIdopgw(Double idopgw) {
		this.idopgw = idopgw;
	}

	public Double getIdopgt() {
		return this.idopgt;
	}

	public void setIdopgt(Double idopgt) {
		this.idopgt = idopgt;
	}

	public Double getIo() {
		return this.io;
	}

	public void setIo(Double io) {
		this.io = io;
	}

	public Double getIoi() {
		return this.ioi;
	}

	public void setIoi(Double ioi) {
		this.ioi = ioi;
	}

	public Double getIan() {
		return this.ian;
	}

	public void setIan(Double ian) {
		this.ian = ian;
	}

	public Double getIanD() {
		return this.ianD;
	}

	public void setIanD(Double ianD) {
		this.ianD = ianD;
	}

	public Double getIr() {
		return this.ir;
	}

	public void setIr(Double ir) {
		this.ir = ir;
	}

	public Double getIg() {
		return this.ig;
	}

	public void setIg(Double ig) {
		this.ig = ig;
	}

	public Double getIgi() {
		return this.igi;
	}

	public void setIgi(Double igi) {
		this.igi = igi;
	}

	public Double getIgtr() {
		return this.igtr;
	}

	public void setIgtr(Double igtr) {
		this.igtr = igtr;
	}

	public Double getIgtri() {
		return this.igtri;
	}

	public void setIgtri(Double igtri) {
		this.igtri = igtri;
	}

	public Double getIos() {
		return this.ios;
	}

	public void setIos(Double ios) {
		this.ios = ios;
	}

	public Double getKwt() {
		return this.kwt;
	}

	public void setKwt(Double kwt) {
		this.kwt = kwt;
	}

	public Double getIosKarm() {
		return this.iosKarm;
	}

	public void setIosKarm(Double iosKarm) {
		this.iosKarm = iosKarm;
	}

	public Double getKwtDop() {
		return this.kwtDop;
	}

	public void setKwtDop(Double kwtDop) {
		this.kwtDop = kwtDop;
	}

	public Double getI101() {
		return this.i101;
	}

	public void setI101(Double i101) {
		this.i101 = i101;
	}

	public Double getIcs() {
		return this.ics;
	}

	public void setIcs(Double ics) {
		this.ics = ics;
	}

	public Double getIao() {
		return this.iao;
	}

	public void setIao(Double iao) {
		this.iao = iao;
	}

	public Double getIkz() {
		return this.ikz;
	}

	public void setIkz(Double ikz) {
		this.ikz = ikz;
	}

	public Double getIer() {
		return this.ier;
	}

	public void setIer(Double ier) {
		this.ier = ier;
	}

	public Double getIkan() {
		return this.ikan;
	}

	public void setIkan(Double ikan) {
		this.ikan = ikan;
	}

	public Double getIkaniz() {
		return this.ikaniz;
	}

	public void setIkaniz(Double ikaniz) {
		this.ikaniz = ikaniz;
	}

	public Double getIdopkan() {
		return this.idopkan;
	}

	public void setIdopkan(Double idopkan) {
		this.idopkan = idopkan;
	}

	public Double getImusor() {
		return this.imusor;
	}

	public void setImusor(Double imusor) {
		this.imusor = imusor;
	}

	public Double getImusi() {
		return this.imusi;
	}

	public void setImusi(Double imusi) {
		this.imusi = imusi;
	}

	public Double getIlif() {
		return this.ilif;
	}

	public void setIlif(Double ilif) {
		this.ilif = ilif;
	}

	public Double getIlifi() {
		return this.ilifi;
	}

	public void setIlifi(Double ilifi) {
		this.ilifi = ilifi;
	}

	public Double getImPr() {
		return this.imPr;
	}

	public void setImPr(Double imPr) {
		this.imPr = imPr;
	}

	public Double getImpri() {
		return this.impri;
	}

	public void setImpri(Double impri) {
		this.impri = impri;
	}

	public Double getIdtPl() {
		return this.idtPl;
	}

	public void setIdtPl(Double idtPl) {
		this.idtPl = idtPl;
	}

	public Double getIkzm() {
		return this.ikzm;
	}

	public void setIkzm(Double ikzm) {
		this.ikzm = ikzm;
	}

	public Double getIelpl() {
		return this.ielpl;
	}

	public void setIelpl(Double ielpl) {
		this.ielpl = ielpl;
	}

	public Double getIrezerv() {
		return this.irezerv;
	}

	public void setIrezerv(Double irezerv) {
		this.irezerv = irezerv;
	}

	public Double getIkPli() {
		return this.ikPli;
	}

	public void setIkPli(Double ikPli) {
		this.ikPli = ikPli;
	}

	public Double getIplel() {
		return this.iplel;
	}

	public void setIplel(Double iplel) {
		this.iplel = iplel;
	}

	public Double getIvaxt() {
		return this.ivaxt;
	}

	public void setIvaxt(Double ivaxt) {
		this.ivaxt = ivaxt;
	}

	public Double getIvaxti() {
		return this.ivaxti;
	}

	public void setIvaxti(Double ivaxti) {
		this.ivaxti = ivaxti;
	}

	public Double getI45() {
		return this.i45;
	}

	public void setI45(Double i45) {
		this.i45 = i45;
	}

	public Double getI46() {
		return this.i46;
	}

	public void setI46(Double i46) {
		this.i46 = i46;
	}

	public Double getI47() {
		return this.i47;
	}

	public void setI47(Double i47) {
		this.i47 = i47;
	}

	public Double getI48() {
		return this.i48;
	}

	public void setI48(Double i48) {
		this.i48 = i48;
	}

	public Double getIknai() {
		return this.iknai;
	}

	public void setIknai(Double iknai) {
		this.iknai = iknai;
	}

	public Double getIland() {
		return this.iland;
	}

	public void setIland(Double iland) {
		this.iland = iland;
	}

	public Double getI49() {
		return this.i49;
	}

	public void setI49(Double i49) {
		this.i49 = i49;
	}

	public Double getI50() {
		return this.i50;
	}

	public void setI50(Double i50) {
		this.i50 = i50;
	}

	public Double getI51() {
		return this.i51;
	}

	public void setI51(Double i51) {
		this.i51 = i51;
	}

	public Double getI52() {
		return this.i52;
	}

	public void setI52(Double i52) {
		this.i52 = i52;
	}

	public Double getI53() {
		return this.i53;
	}

	public void setI53(Double i53) {
		this.i53 = i53;
	}

	public Double getI54() {
		return this.i54;
	}

	public void setI54(Double i54) {
		this.i54 = i54;
	}

	public Double getI55() {
		return this.i55;
	}

	public void setI55(Double i55) {
		this.i55 = i55;
	}

	public Double getI56() {
		return this.i56;
	}

	public void setI56(Double i56) {
		this.i56 = i56;
	}

	public Double getI57() {
		return this.i57;
	}

	public void setI57(Double i57) {
		this.i57 = i57;
	}

	public Double getI58() {
		return this.i58;
	}

	public void setI58(Double i58) {
		this.i58 = i58;
	}

	public Double getI59() {
		return this.i59;
	}

	public void setI59(Double i59) {
		this.i59 = i59;
	}

	public Double getI60() {
		return this.i60;
	}

	public void setI60(Double i60) {
		this.i60 = i60;
	}

	public Double getI61() {
		return this.i61;
	}

	public void setI61(Double i61) {
		this.i61 = i61;
	}

	public Double getHw344() {
		return this.hw344;
	}

	public void setHw344(Double hw344) {
		this.hw344 = hw344;
	}

	public Double getHw344d() {
		return this.hw344d;
	}

	public void setHw344d(Double hw344d) {
		this.hw344d = hw344d;
	}

	public Double getIhw344() {
		return this.ihw344;
	}

	public void setIhw344(Double ihw344) {
		this.ihw344 = ihw344;
	}

	public Double getIhw344d() {
		return this.ihw344d;
	}

	public void setIhw344d(Double ihw344d) {
		this.ihw344d = ihw344d;
	}

	public Double getGw344() {
		return this.gw344;
	}

	public void setGw344(Double gw344) {
		this.gw344 = gw344;
	}

	public Double getGw344d() {
		return this.gw344d;
	}

	public void setGw344d(Double gw344d) {
		this.gw344d = gw344d;
	}

	public Double getIgw344() {
		return this.igw344;
	}

	public void setIgw344(Double igw344) {
		this.igw344 = igw344;
	}

	public Double getIgw344d() {
		return this.igw344d;
	}

	public void setIgw344d(Double igw344d) {
		this.igw344d = igw344d;
	}

	public Double getEl344() {
		return this.el344;
	}

	public void setEl344(Double el344) {
		this.el344 = el344;
	}

	public Double getEl344d() {
		return this.el344d;
	}

	public void setEl344d(Double el344d) {
		this.el344d = el344d;
	}

	public Double getIel344() {
		return this.iel344;
	}

	public void setIel344(Double iel344) {
		this.iel344 = iel344;
	}

	public Double getIel344d() {
		return this.iel344d;
	}

	public void setIel344d(Double iel344d) {
		this.iel344d = iel344d;
	}

	public Double getOt344d() {
		return this.ot344d;
	}

	public void setOt344d(Double ot344d) {
		this.ot344d = ot344d;
	}

	public Double getIot344d() {
		return this.iot344d;
	}

	public void setIot344d(Double iot344d) {
		this.iot344d = iot344d;
	}

	public String getDtizm() {
		return this.dtizm;
	}

	public void setDtizm(String dtizm) {
		this.dtizm = dtizm;
	}

	public String getSchI() {
		return this.schI;
	}

	public void setSchI(String schI) {
		this.schI = schI;
	}

	public Date getDtek() {
		return this.dtek;
	}

	public void setDtek(Date dtek) {
		this.dtek = dtek;
	}

	public String getNkom() {
		return this.nkom;
	}

	public void setNkom(String nkom) {
		this.nkom = nkom;
	}

	public String getPrim() {
		return this.prim;
	}

	public void setPrim(String prim) {
		this.prim = prim;
	}

	public String getLp() {
		return this.lp;
	}

	public void setLp(String lp) {
		this.lp = lp;
	}

	public Double getType() {
		return this.type;
	}

	public void setType(Double type) {
		this.type = type;
	}

	public BigDecimal getI62() {
		return this.i62;
	}

	public void setI62(BigDecimal i62) {
		this.i62 = i62;
	}

	public BigDecimal getI63() {
		return this.i63;
	}

	public void setI63(BigDecimal i63) {
		this.i63 = i63;
	}

	public BigDecimal getI64() {
		return this.i64;
	}

	public void setI64(BigDecimal i64) {
		this.i64 = i64;
	}

	public BigDecimal getI65() {
		return this.i65;
	}

	public void setI65(BigDecimal i65) {
		this.i65 = i65;
	}

	public BigDecimal getI66() {
		return this.i66;
	}

	public void setI66(BigDecimal i66) {
		this.i66 = i66;
	}

	public BigDecimal getI67() {
		return this.i67;
	}

	public void setI67(BigDecimal i67) {
		this.i67 = i67;
	}

	public BigDecimal getI68() {
		return this.i68;
	}

	public void setI68(BigDecimal i68) {
		this.i68 = i68;
	}

	public BigDecimal getI69() {
		return this.i69;
	}

	public void setI69(BigDecimal i69) {
		this.i69 = i69;
	}

	public BigDecimal getI70() {
		return this.i70;
	}

	public void setI70(BigDecimal i70) {
		this.i70 = i70;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KwniId))
			return false;
		KwniId castOther = (KwniId) other;

		return ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
				&& castOther.getLsk() != null && this.getLsk().equals(
				castOther.getLsk())))
				&& ((this.getIkr() == castOther.getIkr()) || (this.getIkr() != null
						&& castOther.getIkr() != null && this.getIkr().equals(
						castOther.getIkr())))
				&& ((this.getIkri() == castOther.getIkri()) || (this.getIkri() != null
						&& castOther.getIkri() != null && this.getIkri()
						.equals(castOther.getIkri())))
				&& ((this.getItr() == castOther.getItr()) || (this.getItr() != null
						&& castOther.getItr() != null && this.getItr().equals(
						castOther.getItr())))
				&& ((this.getItri() == castOther.getItri()) || (this.getItri() != null
						&& castOther.getItri() != null && this.getItri()
						.equals(castOther.getItri())))
				&& ((this.getIder() == castOther.getIder()) || (this.getIder() != null
						&& castOther.getIder() != null && this.getIder()
						.equals(castOther.getIder())))
				&& ((this.getIderi() == castOther.getIderi()) || (this
						.getIderi() != null && castOther.getIderi() != null && this
						.getIderi().equals(castOther.getIderi())))
				&& ((this.getOt() == castOther.getOt()) || (this.getOt() != null
						&& castOther.getOt() != null && this.getOt().equals(
						castOther.getOt())))
				&& ((this.getIot() == castOther.getIot()) || (this.getIot() != null
						&& castOther.getIot() != null && this.getIot().equals(
						castOther.getIot())))
				&& ((this.getIotip() == castOther.getIotip()) || (this
						.getIotip() != null && castOther.getIotip() != null && this
						.getIotip().equals(castOther.getIotip())))
				&& ((this.getIottr() == castOther.getIottr()) || (this
						.getIottr() != null && castOther.getIottr() != null && this
						.getIottr().equals(castOther.getIottr())))
				&& ((this.getIottri() == castOther.getIottri()) || (this
						.getIottri() != null && castOther.getIottri() != null && this
						.getIottri().equals(castOther.getIottri())))
				&& ((this.getHw() == castOther.getHw()) || (this.getHw() != null
						&& castOther.getHw() != null && this.getHw().equals(
						castOther.getHw())))
				&& ((this.getIwod() == castOther.getIwod()) || (this.getIwod() != null
						&& castOther.getIwod() != null && this.getIwod()
						.equals(castOther.getIwod())))
				&& ((this.getIwodiz() == castOther.getIwodiz()) || (this
						.getIwodiz() != null && castOther.getIwodiz() != null && this
						.getIwodiz().equals(castOther.getIwodiz())))
				&& ((this.getIwodtr() == castOther.getIwodtr()) || (this
						.getIwodtr() != null && castOther.getIwodtr() != null && this
						.getIwodtr().equals(castOther.getIwodtr())))
				&& ((this.getIwodtri() == castOther.getIwodtri()) || (this
						.getIwodtri() != null && castOther.getIwodtri() != null && this
						.getIwodtri().equals(castOther.getIwodtri())))
				&& ((this.getHwDop() == castOther.getHwDop()) || (this
						.getHwDop() != null && castOther.getHwDop() != null && this
						.getHwDop().equals(castOther.getHwDop())))
				&& ((this.getIdophw() == castOther.getIdophw()) || (this
						.getIdophw() != null && castOther.getIdophw() != null && this
						.getIdophw().equals(castOther.getIdophw())))
				&& ((this.getIdopht() == castOther.getIdopht()) || (this
						.getIdopht() != null && castOther.getIdopht() != null && this
						.getIdopht().equals(castOther.getIdopht())))
				&& ((this.getGw() == castOther.getGw()) || (this.getGw() != null
						&& castOther.getGw() != null && this.getGw().equals(
						castOther.getGw())))
				&& ((this.getIgw() == castOther.getIgw()) || (this.getIgw() != null
						&& castOther.getIgw() != null && this.getIgw().equals(
						castOther.getIgw())))
				&& ((this.getIgwiz() == castOther.getIgwiz()) || (this
						.getIgwiz() != null && castOther.getIgwiz() != null && this
						.getIgwiz().equals(castOther.getIgwiz())))
				&& ((this.getIgwtr() == castOther.getIgwtr()) || (this
						.getIgwtr() != null && castOther.getIgwtr() != null && this
						.getIgwtr().equals(castOther.getIgwtr())))
				&& ((this.getIgwtri() == castOther.getIgwtri()) || (this
						.getIgwtri() != null && castOther.getIgwtri() != null && this
						.getIgwtri().equals(castOther.getIgwtri())))
				&& ((this.getGwDop() == castOther.getGwDop()) || (this
						.getGwDop() != null && castOther.getGwDop() != null && this
						.getGwDop().equals(castOther.getGwDop())))
				&& ((this.getIdopgw() == castOther.getIdopgw()) || (this
						.getIdopgw() != null && castOther.getIdopgw() != null && this
						.getIdopgw().equals(castOther.getIdopgw())))
				&& ((this.getIdopgt() == castOther.getIdopgt()) || (this
						.getIdopgt() != null && castOther.getIdopgt() != null && this
						.getIdopgt().equals(castOther.getIdopgt())))
				&& ((this.getIo() == castOther.getIo()) || (this.getIo() != null
						&& castOther.getIo() != null && this.getIo().equals(
						castOther.getIo())))
				&& ((this.getIoi() == castOther.getIoi()) || (this.getIoi() != null
						&& castOther.getIoi() != null && this.getIoi().equals(
						castOther.getIoi())))
				&& ((this.getIan() == castOther.getIan()) || (this.getIan() != null
						&& castOther.getIan() != null && this.getIan().equals(
						castOther.getIan())))
				&& ((this.getIanD() == castOther.getIanD()) || (this.getIanD() != null
						&& castOther.getIanD() != null && this.getIanD()
						.equals(castOther.getIanD())))
				&& ((this.getIr() == castOther.getIr()) || (this.getIr() != null
						&& castOther.getIr() != null && this.getIr().equals(
						castOther.getIr())))
				&& ((this.getIg() == castOther.getIg()) || (this.getIg() != null
						&& castOther.getIg() != null && this.getIg().equals(
						castOther.getIg())))
				&& ((this.getIgi() == castOther.getIgi()) || (this.getIgi() != null
						&& castOther.getIgi() != null && this.getIgi().equals(
						castOther.getIgi())))
				&& ((this.getIgtr() == castOther.getIgtr()) || (this.getIgtr() != null
						&& castOther.getIgtr() != null && this.getIgtr()
						.equals(castOther.getIgtr())))
				&& ((this.getIgtri() == castOther.getIgtri()) || (this
						.getIgtri() != null && castOther.getIgtri() != null && this
						.getIgtri().equals(castOther.getIgtri())))
				&& ((this.getIos() == castOther.getIos()) || (this.getIos() != null
						&& castOther.getIos() != null && this.getIos().equals(
						castOther.getIos())))
				&& ((this.getKwt() == castOther.getKwt()) || (this.getKwt() != null
						&& castOther.getKwt() != null && this.getKwt().equals(
						castOther.getKwt())))
				&& ((this.getIosKarm() == castOther.getIosKarm()) || (this
						.getIosKarm() != null && castOther.getIosKarm() != null && this
						.getIosKarm().equals(castOther.getIosKarm())))
				&& ((this.getKwtDop() == castOther.getKwtDop()) || (this
						.getKwtDop() != null && castOther.getKwtDop() != null && this
						.getKwtDop().equals(castOther.getKwtDop())))
				&& ((this.getI101() == castOther.getI101()) || (this.getI101() != null
						&& castOther.getI101() != null && this.getI101()
						.equals(castOther.getI101())))
				&& ((this.getIcs() == castOther.getIcs()) || (this.getIcs() != null
						&& castOther.getIcs() != null && this.getIcs().equals(
						castOther.getIcs())))
				&& ((this.getIao() == castOther.getIao()) || (this.getIao() != null
						&& castOther.getIao() != null && this.getIao().equals(
						castOther.getIao())))
				&& ((this.getIkz() == castOther.getIkz()) || (this.getIkz() != null
						&& castOther.getIkz() != null && this.getIkz().equals(
						castOther.getIkz())))
				&& ((this.getIer() == castOther.getIer()) || (this.getIer() != null
						&& castOther.getIer() != null && this.getIer().equals(
						castOther.getIer())))
				&& ((this.getIkan() == castOther.getIkan()) || (this.getIkan() != null
						&& castOther.getIkan() != null && this.getIkan()
						.equals(castOther.getIkan())))
				&& ((this.getIkaniz() == castOther.getIkaniz()) || (this
						.getIkaniz() != null && castOther.getIkaniz() != null && this
						.getIkaniz().equals(castOther.getIkaniz())))
				&& ((this.getIdopkan() == castOther.getIdopkan()) || (this
						.getIdopkan() != null && castOther.getIdopkan() != null && this
						.getIdopkan().equals(castOther.getIdopkan())))
				&& ((this.getImusor() == castOther.getImusor()) || (this
						.getImusor() != null && castOther.getImusor() != null && this
						.getImusor().equals(castOther.getImusor())))
				&& ((this.getImusi() == castOther.getImusi()) || (this
						.getImusi() != null && castOther.getImusi() != null && this
						.getImusi().equals(castOther.getImusi())))
				&& ((this.getIlif() == castOther.getIlif()) || (this.getIlif() != null
						&& castOther.getIlif() != null && this.getIlif()
						.equals(castOther.getIlif())))
				&& ((this.getIlifi() == castOther.getIlifi()) || (this
						.getIlifi() != null && castOther.getIlifi() != null && this
						.getIlifi().equals(castOther.getIlifi())))
				&& ((this.getImPr() == castOther.getImPr()) || (this.getImPr() != null
						&& castOther.getImPr() != null && this.getImPr()
						.equals(castOther.getImPr())))
				&& ((this.getImpri() == castOther.getImpri()) || (this
						.getImpri() != null && castOther.getImpri() != null && this
						.getImpri().equals(castOther.getImpri())))
				&& ((this.getIdtPl() == castOther.getIdtPl()) || (this
						.getIdtPl() != null && castOther.getIdtPl() != null && this
						.getIdtPl().equals(castOther.getIdtPl())))
				&& ((this.getIkzm() == castOther.getIkzm()) || (this.getIkzm() != null
						&& castOther.getIkzm() != null && this.getIkzm()
						.equals(castOther.getIkzm())))
				&& ((this.getIelpl() == castOther.getIelpl()) || (this
						.getIelpl() != null && castOther.getIelpl() != null && this
						.getIelpl().equals(castOther.getIelpl())))
				&& ((this.getIrezerv() == castOther.getIrezerv()) || (this
						.getIrezerv() != null && castOther.getIrezerv() != null && this
						.getIrezerv().equals(castOther.getIrezerv())))
				&& ((this.getIkPli() == castOther.getIkPli()) || (this
						.getIkPli() != null && castOther.getIkPli() != null && this
						.getIkPli().equals(castOther.getIkPli())))
				&& ((this.getIplel() == castOther.getIplel()) || (this
						.getIplel() != null && castOther.getIplel() != null && this
						.getIplel().equals(castOther.getIplel())))
				&& ((this.getIvaxt() == castOther.getIvaxt()) || (this
						.getIvaxt() != null && castOther.getIvaxt() != null && this
						.getIvaxt().equals(castOther.getIvaxt())))
				&& ((this.getIvaxti() == castOther.getIvaxti()) || (this
						.getIvaxti() != null && castOther.getIvaxti() != null && this
						.getIvaxti().equals(castOther.getIvaxti())))
				&& ((this.getI45() == castOther.getI45()) || (this.getI45() != null
						&& castOther.getI45() != null && this.getI45().equals(
						castOther.getI45())))
				&& ((this.getI46() == castOther.getI46()) || (this.getI46() != null
						&& castOther.getI46() != null && this.getI46().equals(
						castOther.getI46())))
				&& ((this.getI47() == castOther.getI47()) || (this.getI47() != null
						&& castOther.getI47() != null && this.getI47().equals(
						castOther.getI47())))
				&& ((this.getI48() == castOther.getI48()) || (this.getI48() != null
						&& castOther.getI48() != null && this.getI48().equals(
						castOther.getI48())))
				&& ((this.getIknai() == castOther.getIknai()) || (this
						.getIknai() != null && castOther.getIknai() != null && this
						.getIknai().equals(castOther.getIknai())))
				&& ((this.getIland() == castOther.getIland()) || (this
						.getIland() != null && castOther.getIland() != null && this
						.getIland().equals(castOther.getIland())))
				&& ((this.getI49() == castOther.getI49()) || (this.getI49() != null
						&& castOther.getI49() != null && this.getI49().equals(
						castOther.getI49())))
				&& ((this.getI50() == castOther.getI50()) || (this.getI50() != null
						&& castOther.getI50() != null && this.getI50().equals(
						castOther.getI50())))
				&& ((this.getI51() == castOther.getI51()) || (this.getI51() != null
						&& castOther.getI51() != null && this.getI51().equals(
						castOther.getI51())))
				&& ((this.getI52() == castOther.getI52()) || (this.getI52() != null
						&& castOther.getI52() != null && this.getI52().equals(
						castOther.getI52())))
				&& ((this.getI53() == castOther.getI53()) || (this.getI53() != null
						&& castOther.getI53() != null && this.getI53().equals(
						castOther.getI53())))
				&& ((this.getI54() == castOther.getI54()) || (this.getI54() != null
						&& castOther.getI54() != null && this.getI54().equals(
						castOther.getI54())))
				&& ((this.getI55() == castOther.getI55()) || (this.getI55() != null
						&& castOther.getI55() != null && this.getI55().equals(
						castOther.getI55())))
				&& ((this.getI56() == castOther.getI56()) || (this.getI56() != null
						&& castOther.getI56() != null && this.getI56().equals(
						castOther.getI56())))
				&& ((this.getI57() == castOther.getI57()) || (this.getI57() != null
						&& castOther.getI57() != null && this.getI57().equals(
						castOther.getI57())))
				&& ((this.getI58() == castOther.getI58()) || (this.getI58() != null
						&& castOther.getI58() != null && this.getI58().equals(
						castOther.getI58())))
				&& ((this.getI59() == castOther.getI59()) || (this.getI59() != null
						&& castOther.getI59() != null && this.getI59().equals(
						castOther.getI59())))
				&& ((this.getI60() == castOther.getI60()) || (this.getI60() != null
						&& castOther.getI60() != null && this.getI60().equals(
						castOther.getI60())))
				&& ((this.getI61() == castOther.getI61()) || (this.getI61() != null
						&& castOther.getI61() != null && this.getI61().equals(
						castOther.getI61())))
				&& ((this.getHw344() == castOther.getHw344()) || (this
						.getHw344() != null && castOther.getHw344() != null && this
						.getHw344().equals(castOther.getHw344())))
				&& ((this.getHw344d() == castOther.getHw344d()) || (this
						.getHw344d() != null && castOther.getHw344d() != null && this
						.getHw344d().equals(castOther.getHw344d())))
				&& ((this.getIhw344() == castOther.getIhw344()) || (this
						.getIhw344() != null && castOther.getIhw344() != null && this
						.getIhw344().equals(castOther.getIhw344())))
				&& ((this.getIhw344d() == castOther.getIhw344d()) || (this
						.getIhw344d() != null && castOther.getIhw344d() != null && this
						.getIhw344d().equals(castOther.getIhw344d())))
				&& ((this.getGw344() == castOther.getGw344()) || (this
						.getGw344() != null && castOther.getGw344() != null && this
						.getGw344().equals(castOther.getGw344())))
				&& ((this.getGw344d() == castOther.getGw344d()) || (this
						.getGw344d() != null && castOther.getGw344d() != null && this
						.getGw344d().equals(castOther.getGw344d())))
				&& ((this.getIgw344() == castOther.getIgw344()) || (this
						.getIgw344() != null && castOther.getIgw344() != null && this
						.getIgw344().equals(castOther.getIgw344())))
				&& ((this.getIgw344d() == castOther.getIgw344d()) || (this
						.getIgw344d() != null && castOther.getIgw344d() != null && this
						.getIgw344d().equals(castOther.getIgw344d())))
				&& ((this.getEl344() == castOther.getEl344()) || (this
						.getEl344() != null && castOther.getEl344() != null && this
						.getEl344().equals(castOther.getEl344())))
				&& ((this.getEl344d() == castOther.getEl344d()) || (this
						.getEl344d() != null && castOther.getEl344d() != null && this
						.getEl344d().equals(castOther.getEl344d())))
				&& ((this.getIel344() == castOther.getIel344()) || (this
						.getIel344() != null && castOther.getIel344() != null && this
						.getIel344().equals(castOther.getIel344())))
				&& ((this.getIel344d() == castOther.getIel344d()) || (this
						.getIel344d() != null && castOther.getIel344d() != null && this
						.getIel344d().equals(castOther.getIel344d())))
				&& ((this.getOt344d() == castOther.getOt344d()) || (this
						.getOt344d() != null && castOther.getOt344d() != null && this
						.getOt344d().equals(castOther.getOt344d())))
				&& ((this.getIot344d() == castOther.getIot344d()) || (this
						.getIot344d() != null && castOther.getIot344d() != null && this
						.getIot344d().equals(castOther.getIot344d())))
				&& ((this.getDtizm() == castOther.getDtizm()) || (this
						.getDtizm() != null && castOther.getDtizm() != null && this
						.getDtizm().equals(castOther.getDtizm())))
				&& ((this.getSchI() == castOther.getSchI()) || (this.getSchI() != null
						&& castOther.getSchI() != null && this.getSchI()
						.equals(castOther.getSchI())))
				&& ((this.getDtek() == castOther.getDtek()) || (this.getDtek() != null
						&& castOther.getDtek() != null && this.getDtek()
						.equals(castOther.getDtek())))
				&& ((this.getNkom() == castOther.getNkom()) || (this.getNkom() != null
						&& castOther.getNkom() != null && this.getNkom()
						.equals(castOther.getNkom())))
				&& ((this.getPrim() == castOther.getPrim()) || (this.getPrim() != null
						&& castOther.getPrim() != null && this.getPrim()
						.equals(castOther.getPrim())))
				&& ((this.getLp() == castOther.getLp()) || (this.getLp() != null
						&& castOther.getLp() != null && this.getLp().equals(
						castOther.getLp())))
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getI62() == castOther.getI62()) || (this.getI62() != null
						&& castOther.getI62() != null && this.getI62().equals(
						castOther.getI62())))
				&& ((this.getI63() == castOther.getI63()) || (this.getI63() != null
						&& castOther.getI63() != null && this.getI63().equals(
						castOther.getI63())))
				&& ((this.getI64() == castOther.getI64()) || (this.getI64() != null
						&& castOther.getI64() != null && this.getI64().equals(
						castOther.getI64())))
				&& ((this.getI65() == castOther.getI65()) || (this.getI65() != null
						&& castOther.getI65() != null && this.getI65().equals(
						castOther.getI65())))
				&& ((this.getI66() == castOther.getI66()) || (this.getI66() != null
						&& castOther.getI66() != null && this.getI66().equals(
						castOther.getI66())))
				&& ((this.getI67() == castOther.getI67()) || (this.getI67() != null
						&& castOther.getI67() != null && this.getI67().equals(
						castOther.getI67())))
				&& ((this.getI68() == castOther.getI68()) || (this.getI68() != null
						&& castOther.getI68() != null && this.getI68().equals(
						castOther.getI68())))
				&& ((this.getI69() == castOther.getI69()) || (this.getI69() != null
						&& castOther.getI69() != null && this.getI69().equals(
						castOther.getI69())))
				&& ((this.getI70() == castOther.getI70()) || (this.getI70() != null
						&& castOther.getI70() != null && this.getI70().equals(
						castOther.getI70())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getIkr() == null ? 0 : this.getIkr().hashCode());
		result = 37 * result
				+ (getIkri() == null ? 0 : this.getIkri().hashCode());
		result = 37 * result
				+ (getItr() == null ? 0 : this.getItr().hashCode());
		result = 37 * result
				+ (getItri() == null ? 0 : this.getItri().hashCode());
		result = 37 * result
				+ (getIder() == null ? 0 : this.getIder().hashCode());
		result = 37 * result
				+ (getIderi() == null ? 0 : this.getIderi().hashCode());
		result = 37 * result + (getOt() == null ? 0 : this.getOt().hashCode());
		result = 37 * result
				+ (getIot() == null ? 0 : this.getIot().hashCode());
		result = 37 * result
				+ (getIotip() == null ? 0 : this.getIotip().hashCode());
		result = 37 * result
				+ (getIottr() == null ? 0 : this.getIottr().hashCode());
		result = 37 * result
				+ (getIottri() == null ? 0 : this.getIottri().hashCode());
		result = 37 * result + (getHw() == null ? 0 : this.getHw().hashCode());
		result = 37 * result
				+ (getIwod() == null ? 0 : this.getIwod().hashCode());
		result = 37 * result
				+ (getIwodiz() == null ? 0 : this.getIwodiz().hashCode());
		result = 37 * result
				+ (getIwodtr() == null ? 0 : this.getIwodtr().hashCode());
		result = 37 * result
				+ (getIwodtri() == null ? 0 : this.getIwodtri().hashCode());
		result = 37 * result
				+ (getHwDop() == null ? 0 : this.getHwDop().hashCode());
		result = 37 * result
				+ (getIdophw() == null ? 0 : this.getIdophw().hashCode());
		result = 37 * result
				+ (getIdopht() == null ? 0 : this.getIdopht().hashCode());
		result = 37 * result + (getGw() == null ? 0 : this.getGw().hashCode());
		result = 37 * result
				+ (getIgw() == null ? 0 : this.getIgw().hashCode());
		result = 37 * result
				+ (getIgwiz() == null ? 0 : this.getIgwiz().hashCode());
		result = 37 * result
				+ (getIgwtr() == null ? 0 : this.getIgwtr().hashCode());
		result = 37 * result
				+ (getIgwtri() == null ? 0 : this.getIgwtri().hashCode());
		result = 37 * result
				+ (getGwDop() == null ? 0 : this.getGwDop().hashCode());
		result = 37 * result
				+ (getIdopgw() == null ? 0 : this.getIdopgw().hashCode());
		result = 37 * result
				+ (getIdopgt() == null ? 0 : this.getIdopgt().hashCode());
		result = 37 * result + (getIo() == null ? 0 : this.getIo().hashCode());
		result = 37 * result
				+ (getIoi() == null ? 0 : this.getIoi().hashCode());
		result = 37 * result
				+ (getIan() == null ? 0 : this.getIan().hashCode());
		result = 37 * result
				+ (getIanD() == null ? 0 : this.getIanD().hashCode());
		result = 37 * result + (getIr() == null ? 0 : this.getIr().hashCode());
		result = 37 * result + (getIg() == null ? 0 : this.getIg().hashCode());
		result = 37 * result
				+ (getIgi() == null ? 0 : this.getIgi().hashCode());
		result = 37 * result
				+ (getIgtr() == null ? 0 : this.getIgtr().hashCode());
		result = 37 * result
				+ (getIgtri() == null ? 0 : this.getIgtri().hashCode());
		result = 37 * result
				+ (getIos() == null ? 0 : this.getIos().hashCode());
		result = 37 * result
				+ (getKwt() == null ? 0 : this.getKwt().hashCode());
		result = 37 * result
				+ (getIosKarm() == null ? 0 : this.getIosKarm().hashCode());
		result = 37 * result
				+ (getKwtDop() == null ? 0 : this.getKwtDop().hashCode());
		result = 37 * result
				+ (getI101() == null ? 0 : this.getI101().hashCode());
		result = 37 * result
				+ (getIcs() == null ? 0 : this.getIcs().hashCode());
		result = 37 * result
				+ (getIao() == null ? 0 : this.getIao().hashCode());
		result = 37 * result
				+ (getIkz() == null ? 0 : this.getIkz().hashCode());
		result = 37 * result
				+ (getIer() == null ? 0 : this.getIer().hashCode());
		result = 37 * result
				+ (getIkan() == null ? 0 : this.getIkan().hashCode());
		result = 37 * result
				+ (getIkaniz() == null ? 0 : this.getIkaniz().hashCode());
		result = 37 * result
				+ (getIdopkan() == null ? 0 : this.getIdopkan().hashCode());
		result = 37 * result
				+ (getImusor() == null ? 0 : this.getImusor().hashCode());
		result = 37 * result
				+ (getImusi() == null ? 0 : this.getImusi().hashCode());
		result = 37 * result
				+ (getIlif() == null ? 0 : this.getIlif().hashCode());
		result = 37 * result
				+ (getIlifi() == null ? 0 : this.getIlifi().hashCode());
		result = 37 * result
				+ (getImPr() == null ? 0 : this.getImPr().hashCode());
		result = 37 * result
				+ (getImpri() == null ? 0 : this.getImpri().hashCode());
		result = 37 * result
				+ (getIdtPl() == null ? 0 : this.getIdtPl().hashCode());
		result = 37 * result
				+ (getIkzm() == null ? 0 : this.getIkzm().hashCode());
		result = 37 * result
				+ (getIelpl() == null ? 0 : this.getIelpl().hashCode());
		result = 37 * result
				+ (getIrezerv() == null ? 0 : this.getIrezerv().hashCode());
		result = 37 * result
				+ (getIkPli() == null ? 0 : this.getIkPli().hashCode());
		result = 37 * result
				+ (getIplel() == null ? 0 : this.getIplel().hashCode());
		result = 37 * result
				+ (getIvaxt() == null ? 0 : this.getIvaxt().hashCode());
		result = 37 * result
				+ (getIvaxti() == null ? 0 : this.getIvaxti().hashCode());
		result = 37 * result
				+ (getI45() == null ? 0 : this.getI45().hashCode());
		result = 37 * result
				+ (getI46() == null ? 0 : this.getI46().hashCode());
		result = 37 * result
				+ (getI47() == null ? 0 : this.getI47().hashCode());
		result = 37 * result
				+ (getI48() == null ? 0 : this.getI48().hashCode());
		result = 37 * result
				+ (getIknai() == null ? 0 : this.getIknai().hashCode());
		result = 37 * result
				+ (getIland() == null ? 0 : this.getIland().hashCode());
		result = 37 * result
				+ (getI49() == null ? 0 : this.getI49().hashCode());
		result = 37 * result
				+ (getI50() == null ? 0 : this.getI50().hashCode());
		result = 37 * result
				+ (getI51() == null ? 0 : this.getI51().hashCode());
		result = 37 * result
				+ (getI52() == null ? 0 : this.getI52().hashCode());
		result = 37 * result
				+ (getI53() == null ? 0 : this.getI53().hashCode());
		result = 37 * result
				+ (getI54() == null ? 0 : this.getI54().hashCode());
		result = 37 * result
				+ (getI55() == null ? 0 : this.getI55().hashCode());
		result = 37 * result
				+ (getI56() == null ? 0 : this.getI56().hashCode());
		result = 37 * result
				+ (getI57() == null ? 0 : this.getI57().hashCode());
		result = 37 * result
				+ (getI58() == null ? 0 : this.getI58().hashCode());
		result = 37 * result
				+ (getI59() == null ? 0 : this.getI59().hashCode());
		result = 37 * result
				+ (getI60() == null ? 0 : this.getI60().hashCode());
		result = 37 * result
				+ (getI61() == null ? 0 : this.getI61().hashCode());
		result = 37 * result
				+ (getHw344() == null ? 0 : this.getHw344().hashCode());
		result = 37 * result
				+ (getHw344d() == null ? 0 : this.getHw344d().hashCode());
		result = 37 * result
				+ (getIhw344() == null ? 0 : this.getIhw344().hashCode());
		result = 37 * result
				+ (getIhw344d() == null ? 0 : this.getIhw344d().hashCode());
		result = 37 * result
				+ (getGw344() == null ? 0 : this.getGw344().hashCode());
		result = 37 * result
				+ (getGw344d() == null ? 0 : this.getGw344d().hashCode());
		result = 37 * result
				+ (getIgw344() == null ? 0 : this.getIgw344().hashCode());
		result = 37 * result
				+ (getIgw344d() == null ? 0 : this.getIgw344d().hashCode());
		result = 37 * result
				+ (getEl344() == null ? 0 : this.getEl344().hashCode());
		result = 37 * result
				+ (getEl344d() == null ? 0 : this.getEl344d().hashCode());
		result = 37 * result
				+ (getIel344() == null ? 0 : this.getIel344().hashCode());
		result = 37 * result
				+ (getIel344d() == null ? 0 : this.getIel344d().hashCode());
		result = 37 * result
				+ (getOt344d() == null ? 0 : this.getOt344d().hashCode());
		result = 37 * result
				+ (getIot344d() == null ? 0 : this.getIot344d().hashCode());
		result = 37 * result
				+ (getDtizm() == null ? 0 : this.getDtizm().hashCode());
		result = 37 * result
				+ (getSchI() == null ? 0 : this.getSchI().hashCode());
		result = 37 * result
				+ (getDtek() == null ? 0 : this.getDtek().hashCode());
		result = 37 * result
				+ (getNkom() == null ? 0 : this.getNkom().hashCode());
		result = 37 * result
				+ (getPrim() == null ? 0 : this.getPrim().hashCode());
		result = 37 * result + (getLp() == null ? 0 : this.getLp().hashCode());
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getI62() == null ? 0 : this.getI62().hashCode());
		result = 37 * result
				+ (getI63() == null ? 0 : this.getI63().hashCode());
		result = 37 * result
				+ (getI64() == null ? 0 : this.getI64().hashCode());
		result = 37 * result
				+ (getI65() == null ? 0 : this.getI65().hashCode());
		result = 37 * result
				+ (getI66() == null ? 0 : this.getI66().hashCode());
		result = 37 * result
				+ (getI67() == null ? 0 : this.getI67().hashCode());
		result = 37 * result
				+ (getI68() == null ? 0 : this.getI68().hashCode());
		result = 37 * result
				+ (getI69() == null ? 0 : this.getI69().hashCode());
		result = 37 * result
				+ (getI70() == null ? 0 : this.getI70().hashCode());
		return result;
	}

}
