package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * Kwni generated by hbm2java
 */
public class Kwni implements java.io.Serializable {

	private KwniId id;

	public Kwni() {
	}

	public Kwni(KwniId id) {
		this.id = id;
	}

	public KwniId getId() {
		return this.id;
	}

	public void setId(KwniId id) {
		this.id = id;
	}

}
