package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LChrg generated by hbm2java
 */
public class LChrg implements java.io.Serializable {

	private LChrgId id;

	public LChrg() {
	}

	public LChrg(LChrgId id) {
		this.id = id;
	}

	public LChrgId getId() {
		return this.id;
	}

	public void setId(LChrgId id) {
		this.id = id;
	}

}
