package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LDolgi generated by hbm2java
 */
public class LDolgi implements java.io.Serializable {

	private LDolgiId id;

	public LDolgi() {
	}

	public LDolgi(LDolgiId id) {
		this.id = id;
	}

	public LDolgiId getId() {
		return this.id;
	}

	public void setId(LDolgiId id) {
		this.id = id;
	}

}
