package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LDolgiId generated by hbm2java
 */
public class LDolgiId implements java.io.Serializable {

	private String lsk;
	private String oper;
	private BigDecimal dolg;
	private BigDecimal ostDolg;
	private String ndog;
	private Date datVvod;
	private String adr;
	private String nmpotr;

	public LDolgiId() {
	}

	public LDolgiId(String lsk, String oper, BigDecimal dolg,
			BigDecimal ostDolg, String ndog, Date datVvod, String adr,
			String nmpotr) {
		this.lsk = lsk;
		this.oper = oper;
		this.dolg = dolg;
		this.ostDolg = ostDolg;
		this.ndog = ndog;
		this.datVvod = datVvod;
		this.adr = adr;
		this.nmpotr = nmpotr;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public String getOper() {
		return this.oper;
	}

	public void setOper(String oper) {
		this.oper = oper;
	}

	public BigDecimal getDolg() {
		return this.dolg;
	}

	public void setDolg(BigDecimal dolg) {
		this.dolg = dolg;
	}

	public BigDecimal getOstDolg() {
		return this.ostDolg;
	}

	public void setOstDolg(BigDecimal ostDolg) {
		this.ostDolg = ostDolg;
	}

	public String getNdog() {
		return this.ndog;
	}

	public void setNdog(String ndog) {
		this.ndog = ndog;
	}

	public Date getDatVvod() {
		return this.datVvod;
	}

	public void setDatVvod(Date datVvod) {
		this.datVvod = datVvod;
	}

	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	public String getNmpotr() {
		return this.nmpotr;
	}

	public void setNmpotr(String nmpotr) {
		this.nmpotr = nmpotr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LDolgiId))
			return false;
		LDolgiId castOther = (LDolgiId) other;

		return ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
				&& castOther.getLsk() != null && this.getLsk().equals(
				castOther.getLsk())))
				&& ((this.getOper() == castOther.getOper()) || (this.getOper() != null
						&& castOther.getOper() != null && this.getOper()
						.equals(castOther.getOper())))
				&& ((this.getDolg() == castOther.getDolg()) || (this.getDolg() != null
						&& castOther.getDolg() != null && this.getDolg()
						.equals(castOther.getDolg())))
				&& ((this.getOstDolg() == castOther.getOstDolg()) || (this
						.getOstDolg() != null && castOther.getOstDolg() != null && this
						.getOstDolg().equals(castOther.getOstDolg())))
				&& ((this.getNdog() == castOther.getNdog()) || (this.getNdog() != null
						&& castOther.getNdog() != null && this.getNdog()
						.equals(castOther.getNdog())))
				&& ((this.getDatVvod() == castOther.getDatVvod()) || (this
						.getDatVvod() != null && castOther.getDatVvod() != null && this
						.getDatVvod().equals(castOther.getDatVvod())))
				&& ((this.getAdr() == castOther.getAdr()) || (this.getAdr() != null
						&& castOther.getAdr() != null && this.getAdr().equals(
						castOther.getAdr())))
				&& ((this.getNmpotr() == castOther.getNmpotr()) || (this
						.getNmpotr() != null && castOther.getNmpotr() != null && this
						.getNmpotr().equals(castOther.getNmpotr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getOper() == null ? 0 : this.getOper().hashCode());
		result = 37 * result
				+ (getDolg() == null ? 0 : this.getDolg().hashCode());
		result = 37 * result
				+ (getOstDolg() == null ? 0 : this.getOstDolg().hashCode());
		result = 37 * result
				+ (getNdog() == null ? 0 : this.getNdog().hashCode());
		result = 37 * result
				+ (getDatVvod() == null ? 0 : this.getDatVvod().hashCode());
		result = 37 * result
				+ (getAdr() == null ? 0 : this.getAdr().hashCode());
		result = 37 * result
				+ (getNmpotr() == null ? 0 : this.getNmpotr().hashCode());
		return result;
	}

}
