package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LKartwebId generated by hbm2java
 */
public class LKartwebId implements java.io.Serializable {

	private BigDecimal CLskId;
	private String hash;
	private BigDecimal idLegal;
	private BigDecimal idLegdep;
	private Date dtEnd;
	private BigDecimal idState;
	private String CHash;
	private String kul;
	private String nd;
	private String kw;
	private BigDecimal idKartweb;
	private Date dtBeg;
	private String ymSch;
	private BigDecimal status;

	public LKartwebId() {
	}

	public LKartwebId(BigDecimal CLskId) {
		this.CLskId = CLskId;
	}

	public LKartwebId(BigDecimal CLskId, String hash, BigDecimal idLegal,
			BigDecimal idLegdep, Date dtEnd, BigDecimal idState, String CHash,
			String kul, String nd, String kw, BigDecimal idKartweb, Date dtBeg,
			String ymSch, BigDecimal status) {
		this.CLskId = CLskId;
		this.hash = hash;
		this.idLegal = idLegal;
		this.idLegdep = idLegdep;
		this.dtEnd = dtEnd;
		this.idState = idState;
		this.CHash = CHash;
		this.kul = kul;
		this.nd = nd;
		this.kw = kw;
		this.idKartweb = idKartweb;
		this.dtBeg = dtBeg;
		this.ymSch = ymSch;
		this.status = status;
	}

	public BigDecimal getCLskId() {
		return this.CLskId;
	}

	public void setCLskId(BigDecimal CLskId) {
		this.CLskId = CLskId;
	}

	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public BigDecimal getIdLegal() {
		return this.idLegal;
	}

	public void setIdLegal(BigDecimal idLegal) {
		this.idLegal = idLegal;
	}

	public BigDecimal getIdLegdep() {
		return this.idLegdep;
	}

	public void setIdLegdep(BigDecimal idLegdep) {
		this.idLegdep = idLegdep;
	}

	public Date getDtEnd() {
		return this.dtEnd;
	}

	public void setDtEnd(Date dtEnd) {
		this.dtEnd = dtEnd;
	}

	public BigDecimal getIdState() {
		return this.idState;
	}

	public void setIdState(BigDecimal idState) {
		this.idState = idState;
	}

	public String getCHash() {
		return this.CHash;
	}

	public void setCHash(String CHash) {
		this.CHash = CHash;
	}

	public String getKul() {
		return this.kul;
	}

	public void setKul(String kul) {
		this.kul = kul;
	}

	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	public String getKw() {
		return this.kw;
	}

	public void setKw(String kw) {
		this.kw = kw;
	}

	public BigDecimal getIdKartweb() {
		return this.idKartweb;
	}

	public void setIdKartweb(BigDecimal idKartweb) {
		this.idKartweb = idKartweb;
	}

	public Date getDtBeg() {
		return this.dtBeg;
	}

	public void setDtBeg(Date dtBeg) {
		this.dtBeg = dtBeg;
	}

	public String getYmSch() {
		return this.ymSch;
	}

	public void setYmSch(String ymSch) {
		this.ymSch = ymSch;
	}

	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LKartwebId))
			return false;
		LKartwebId castOther = (LKartwebId) other;

		return ((this.getCLskId() == castOther.getCLskId()) || (this
				.getCLskId() != null && castOther.getCLskId() != null && this
				.getCLskId().equals(castOther.getCLskId())))
				&& ((this.getHash() == castOther.getHash()) || (this.getHash() != null
						&& castOther.getHash() != null && this.getHash()
						.equals(castOther.getHash())))
				&& ((this.getIdLegal() == castOther.getIdLegal()) || (this
						.getIdLegal() != null && castOther.getIdLegal() != null && this
						.getIdLegal().equals(castOther.getIdLegal())))
				&& ((this.getIdLegdep() == castOther.getIdLegdep()) || (this
						.getIdLegdep() != null
						&& castOther.getIdLegdep() != null && this
						.getIdLegdep().equals(castOther.getIdLegdep())))
				&& ((this.getDtEnd() == castOther.getDtEnd()) || (this
						.getDtEnd() != null && castOther.getDtEnd() != null && this
						.getDtEnd().equals(castOther.getDtEnd())))
				&& ((this.getIdState() == castOther.getIdState()) || (this
						.getIdState() != null && castOther.getIdState() != null && this
						.getIdState().equals(castOther.getIdState())))
				&& ((this.getCHash() == castOther.getCHash()) || (this
						.getCHash() != null && castOther.getCHash() != null && this
						.getCHash().equals(castOther.getCHash())))
				&& ((this.getKul() == castOther.getKul()) || (this.getKul() != null
						&& castOther.getKul() != null && this.getKul().equals(
						castOther.getKul())))
				&& ((this.getNd() == castOther.getNd()) || (this.getNd() != null
						&& castOther.getNd() != null && this.getNd().equals(
						castOther.getNd())))
				&& ((this.getKw() == castOther.getKw()) || (this.getKw() != null
						&& castOther.getKw() != null && this.getKw().equals(
						castOther.getKw())))
				&& ((this.getIdKartweb() == castOther.getIdKartweb()) || (this
						.getIdKartweb() != null
						&& castOther.getIdKartweb() != null && this
						.getIdKartweb().equals(castOther.getIdKartweb())))
				&& ((this.getDtBeg() == castOther.getDtBeg()) || (this
						.getDtBeg() != null && castOther.getDtBeg() != null && this
						.getDtBeg().equals(castOther.getDtBeg())))
				&& ((this.getYmSch() == castOther.getYmSch()) || (this
						.getYmSch() != null && castOther.getYmSch() != null && this
						.getYmSch().equals(castOther.getYmSch())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCLskId() == null ? 0 : this.getCLskId().hashCode());
		result = 37 * result
				+ (getHash() == null ? 0 : this.getHash().hashCode());
		result = 37 * result
				+ (getIdLegal() == null ? 0 : this.getIdLegal().hashCode());
		result = 37 * result
				+ (getIdLegdep() == null ? 0 : this.getIdLegdep().hashCode());
		result = 37 * result
				+ (getDtEnd() == null ? 0 : this.getDtEnd().hashCode());
		result = 37 * result
				+ (getIdState() == null ? 0 : this.getIdState().hashCode());
		result = 37 * result
				+ (getCHash() == null ? 0 : this.getCHash().hashCode());
		result = 37 * result
				+ (getKul() == null ? 0 : this.getKul().hashCode());
		result = 37 * result + (getNd() == null ? 0 : this.getNd().hashCode());
		result = 37 * result + (getKw() == null ? 0 : this.getKw().hashCode());
		result = 37 * result
				+ (getIdKartweb() == null ? 0 : this.getIdKartweb().hashCode());
		result = 37 * result
				+ (getDtBeg() == null ? 0 : this.getDtBeg().hashCode());
		result = 37 * result
				+ (getYmSch() == null ? 0 : this.getYmSch().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
