package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LKartweb generated by hbm2java
 */
public class LKartweb implements java.io.Serializable {

	private LKartwebId id;

	public LKartweb() {
	}

	public LKartweb(LKartwebId id) {
		this.id = id;
	}

	public LKartwebId getId() {
		return this.id;
	}

	public void setId(LKartwebId id) {
		this.id = id;
	}

}
