package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * LMestorabId generated by hbm2java
 */
public class LMestorabId implements java.io.Serializable {

	private String lsk;
	private BigDecimal nomer;
	private String mestor;
	private BigDecimal rabtelef;
	private BigDecimal sotov;

	public LMestorabId() {
	}

	public LMestorabId(String lsk) {
		this.lsk = lsk;
	}

	public LMestorabId(String lsk, BigDecimal nomer, String mestor,
			BigDecimal rabtelef, BigDecimal sotov) {
		this.lsk = lsk;
		this.nomer = nomer;
		this.mestor = mestor;
		this.rabtelef = rabtelef;
		this.sotov = sotov;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public BigDecimal getNomer() {
		return this.nomer;
	}

	public void setNomer(BigDecimal nomer) {
		this.nomer = nomer;
	}

	public String getMestor() {
		return this.mestor;
	}

	public void setMestor(String mestor) {
		this.mestor = mestor;
	}

	public BigDecimal getRabtelef() {
		return this.rabtelef;
	}

	public void setRabtelef(BigDecimal rabtelef) {
		this.rabtelef = rabtelef;
	}

	public BigDecimal getSotov() {
		return this.sotov;
	}

	public void setSotov(BigDecimal sotov) {
		this.sotov = sotov;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LMestorabId))
			return false;
		LMestorabId castOther = (LMestorabId) other;

		return ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
				&& castOther.getLsk() != null && this.getLsk().equals(
				castOther.getLsk())))
				&& ((this.getNomer() == castOther.getNomer()) || (this
						.getNomer() != null && castOther.getNomer() != null && this
						.getNomer().equals(castOther.getNomer())))
				&& ((this.getMestor() == castOther.getMestor()) || (this
						.getMestor() != null && castOther.getMestor() != null && this
						.getMestor().equals(castOther.getMestor())))
				&& ((this.getRabtelef() == castOther.getRabtelef()) || (this
						.getRabtelef() != null
						&& castOther.getRabtelef() != null && this
						.getRabtelef().equals(castOther.getRabtelef())))
				&& ((this.getSotov() == castOther.getSotov()) || (this
						.getSotov() != null && castOther.getSotov() != null && this
						.getSotov().equals(castOther.getSotov())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getNomer() == null ? 0 : this.getNomer().hashCode());
		result = 37 * result
				+ (getMestor() == null ? 0 : this.getMestor().hashCode());
		result = 37 * result
				+ (getRabtelef() == null ? 0 : this.getRabtelef().hashCode());
		result = 37 * result
				+ (getSotov() == null ? 0 : this.getSotov().hashCode());
		return result;
	}

}
