package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LMestorab generated by hbm2java
 */
public class LMestorab implements java.io.Serializable {

	private LMestorabId id;

	public LMestorab() {
	}

	public LMestorab(LMestorabId id) {
		this.id = id;
	}

	public LMestorabId getId() {
		return this.id;
	}

	public void setId(LMestorabId id) {
		this.id = id;
	}

}
