package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * LNpgId generated by hbm2java
 */
public class LNpgId implements java.io.Serializable {

	private String lsk;
	private BigDecimal summa;
	private String mg;

	public LNpgId() {
	}

	public LNpgId(String lsk, BigDecimal summa, String mg) {
		this.lsk = lsk;
		this.summa = summa;
		this.mg = mg;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public BigDecimal getSumma() {
		return this.summa;
	}

	public void setSumma(BigDecimal summa) {
		this.summa = summa;
	}

	public String getMg() {
		return this.mg;
	}

	public void setMg(String mg) {
		this.mg = mg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LNpgId))
			return false;
		LNpgId castOther = (LNpgId) other;

		return ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
				&& castOther.getLsk() != null && this.getLsk().equals(
				castOther.getLsk())))
				&& ((this.getSumma() == castOther.getSumma()) || (this
						.getSumma() != null && castOther.getSumma() != null && this
						.getSumma().equals(castOther.getSumma())))
				&& ((this.getMg() == castOther.getMg()) || (this.getMg() != null
						&& castOther.getMg() != null && this.getMg().equals(
						castOther.getMg())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getSumma() == null ? 0 : this.getSumma().hashCode());
		result = 37 * result + (getMg() == null ? 0 : this.getMg().hashCode());
		return result;
	}

}
