package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LNpg generated by hbm2java
 */
public class LNpg implements java.io.Serializable {

	private LNpgId id;

	public LNpg() {
	}

	public LNpg(LNpgId id) {
		this.id = id;
	}

	public LNpgId getId() {
		return this.id;
	}

	public void setId(LNpgId id) {
		this.id = id;
	}

}
