package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LPrnk generated by hbm2java
 */
public class LPrnk implements java.io.Serializable {

	private LPrnkId id;

	public LPrnk() {
	}

	public LPrnk(LPrnkId id) {
		this.id = id;
	}

	public LPrnkId getId() {
		return this.id;
	}

	public void setId(LPrnkId id) {
		this.id = id;
	}

}
