package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LSaldo generated by hbm2java
 */
public class LSaldo implements java.io.Serializable {

	private LSaldoId id;

	public LSaldo() {
	}

	public LSaldo(LSaldoId id) {
		this.id = id;
	}

	public LSaldoId getId() {
		return this.id;
	}

	public void setId(LSaldoId id) {
		this.id = id;
	}

}
