package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LskGuid generated by hbm2java
 */
public class LskGuid implements java.io.Serializable {

	private LskGuidId id;

	public LskGuid() {
	}

	public LskGuid(LskGuidId id) {
		this.id = id;
	}

	public LskGuidId getId() {
		return this.id;
	}

	public void setId(LskGuidId id) {
		this.id = id;
	}

}
