package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * LStraInf generated by hbm2java
 */
public class LStraInf implements java.io.Serializable {

	private LStraInfId id;

	public LStraInf() {
	}

	public LStraInf(LStraInfId id) {
		this.id = id;
	}

	public LStraInfId getId() {
		return this.id;
	}

	public void setId(LStraInfId id) {
		this.id = id;
	}

}
