package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * LStraInfId generated by hbm2java
 */
public class LStraInfId implements java.io.Serializable {

	private String stra;
	private String uslOper;
	private BigDecimal tarif;
	private String str1;
	private String str2;
	private String str3;
	private String str4;
	private String str5;
	private String str6;
	private String str7;
	private String str8;
	private String str9;
	private String str1_1;
	private String str2_1;
	private String str3_1;
	private String str4_1;
	private String str5_1;

	public LStraInfId() {
	}

	public LStraInfId(String stra, String uslOper, BigDecimal tarif,
			String str1, String str2, String str3, String str4, String str5,
			String str6, String str7, String str8, String str9, String str1_1,
			String str2_1, String str3_1, String str4_1, String str5_1) {
		this.stra = stra;
		this.uslOper = uslOper;
		this.tarif = tarif;
		this.str1 = str1;
		this.str2 = str2;
		this.str3 = str3;
		this.str4 = str4;
		this.str5 = str5;
		this.str6 = str6;
		this.str7 = str7;
		this.str8 = str8;
		this.str9 = str9;
		this.str1_1 = str1_1;
		this.str2_1 = str2_1;
		this.str3_1 = str3_1;
		this.str4_1 = str4_1;
		this.str5_1 = str5_1;
	}

	public String getStra() {
		return this.stra;
	}

	public void setStra(String stra) {
		this.stra = stra;
	}

	public String getUslOper() {
		return this.uslOper;
	}

	public void setUslOper(String uslOper) {
		this.uslOper = uslOper;
	}

	public BigDecimal getTarif() {
		return this.tarif;
	}

	public void setTarif(BigDecimal tarif) {
		this.tarif = tarif;
	}

	public String getStr1() {
		return this.str1;
	}

	public void setStr1(String str1) {
		this.str1 = str1;
	}

	public String getStr2() {
		return this.str2;
	}

	public void setStr2(String str2) {
		this.str2 = str2;
	}

	public String getStr3() {
		return this.str3;
	}

	public void setStr3(String str3) {
		this.str3 = str3;
	}

	public String getStr4() {
		return this.str4;
	}

	public void setStr4(String str4) {
		this.str4 = str4;
	}

	public String getStr5() {
		return this.str5;
	}

	public void setStr5(String str5) {
		this.str5 = str5;
	}

	public String getStr6() {
		return this.str6;
	}

	public void setStr6(String str6) {
		this.str6 = str6;
	}

	public String getStr7() {
		return this.str7;
	}

	public void setStr7(String str7) {
		this.str7 = str7;
	}

	public String getStr8() {
		return this.str8;
	}

	public void setStr8(String str8) {
		this.str8 = str8;
	}

	public String getStr9() {
		return this.str9;
	}

	public void setStr9(String str9) {
		this.str9 = str9;
	}

	public String getStr1_1() {
		return this.str1_1;
	}

	public void setStr1_1(String str1_1) {
		this.str1_1 = str1_1;
	}

	public String getStr2_1() {
		return this.str2_1;
	}

	public void setStr2_1(String str2_1) {
		this.str2_1 = str2_1;
	}

	public String getStr3_1() {
		return this.str3_1;
	}

	public void setStr3_1(String str3_1) {
		this.str3_1 = str3_1;
	}

	public String getStr4_1() {
		return this.str4_1;
	}

	public void setStr4_1(String str4_1) {
		this.str4_1 = str4_1;
	}

	public String getStr5_1() {
		return this.str5_1;
	}

	public void setStr5_1(String str5_1) {
		this.str5_1 = str5_1;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LStraInfId))
			return false;
		LStraInfId castOther = (LStraInfId) other;

		return ((this.getStra() == castOther.getStra()) || (this.getStra() != null
				&& castOther.getStra() != null && this.getStra().equals(
				castOther.getStra())))
				&& ((this.getUslOper() == castOther.getUslOper()) || (this
						.getUslOper() != null && castOther.getUslOper() != null && this
						.getUslOper().equals(castOther.getUslOper())))
				&& ((this.getTarif() == castOther.getTarif()) || (this
						.getTarif() != null && castOther.getTarif() != null && this
						.getTarif().equals(castOther.getTarif())))
				&& ((this.getStr1() == castOther.getStr1()) || (this.getStr1() != null
						&& castOther.getStr1() != null && this.getStr1()
						.equals(castOther.getStr1())))
				&& ((this.getStr2() == castOther.getStr2()) || (this.getStr2() != null
						&& castOther.getStr2() != null && this.getStr2()
						.equals(castOther.getStr2())))
				&& ((this.getStr3() == castOther.getStr3()) || (this.getStr3() != null
						&& castOther.getStr3() != null && this.getStr3()
						.equals(castOther.getStr3())))
				&& ((this.getStr4() == castOther.getStr4()) || (this.getStr4() != null
						&& castOther.getStr4() != null && this.getStr4()
						.equals(castOther.getStr4())))
				&& ((this.getStr5() == castOther.getStr5()) || (this.getStr5() != null
						&& castOther.getStr5() != null && this.getStr5()
						.equals(castOther.getStr5())))
				&& ((this.getStr6() == castOther.getStr6()) || (this.getStr6() != null
						&& castOther.getStr6() != null && this.getStr6()
						.equals(castOther.getStr6())))
				&& ((this.getStr7() == castOther.getStr7()) || (this.getStr7() != null
						&& castOther.getStr7() != null && this.getStr7()
						.equals(castOther.getStr7())))
				&& ((this.getStr8() == castOther.getStr8()) || (this.getStr8() != null
						&& castOther.getStr8() != null && this.getStr8()
						.equals(castOther.getStr8())))
				&& ((this.getStr9() == castOther.getStr9()) || (this.getStr9() != null
						&& castOther.getStr9() != null && this.getStr9()
						.equals(castOther.getStr9())))
				&& ((this.getStr1_1() == castOther.getStr1_1()) || (this
						.getStr1_1() != null && castOther.getStr1_1() != null && this
						.getStr1_1().equals(castOther.getStr1_1())))
				&& ((this.getStr2_1() == castOther.getStr2_1()) || (this
						.getStr2_1() != null && castOther.getStr2_1() != null && this
						.getStr2_1().equals(castOther.getStr2_1())))
				&& ((this.getStr3_1() == castOther.getStr3_1()) || (this
						.getStr3_1() != null && castOther.getStr3_1() != null && this
						.getStr3_1().equals(castOther.getStr3_1())))
				&& ((this.getStr4_1() == castOther.getStr4_1()) || (this
						.getStr4_1() != null && castOther.getStr4_1() != null && this
						.getStr4_1().equals(castOther.getStr4_1())))
				&& ((this.getStr5_1() == castOther.getStr5_1()) || (this
						.getStr5_1() != null && castOther.getStr5_1() != null && this
						.getStr5_1().equals(castOther.getStr5_1())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStra() == null ? 0 : this.getStra().hashCode());
		result = 37 * result
				+ (getUslOper() == null ? 0 : this.getUslOper().hashCode());
		result = 37 * result
				+ (getTarif() == null ? 0 : this.getTarif().hashCode());
		result = 37 * result
				+ (getStr1() == null ? 0 : this.getStr1().hashCode());
		result = 37 * result
				+ (getStr2() == null ? 0 : this.getStr2().hashCode());
		result = 37 * result
				+ (getStr3() == null ? 0 : this.getStr3().hashCode());
		result = 37 * result
				+ (getStr4() == null ? 0 : this.getStr4().hashCode());
		result = 37 * result
				+ (getStr5() == null ? 0 : this.getStr5().hashCode());
		result = 37 * result
				+ (getStr6() == null ? 0 : this.getStr6().hashCode());
		result = 37 * result
				+ (getStr7() == null ? 0 : this.getStr7().hashCode());
		result = 37 * result
				+ (getStr8() == null ? 0 : this.getStr8().hashCode());
		result = 37 * result
				+ (getStr9() == null ? 0 : this.getStr9().hashCode());
		result = 37 * result
				+ (getStr1_1() == null ? 0 : this.getStr1_1().hashCode());
		result = 37 * result
				+ (getStr2_1() == null ? 0 : this.getStr2_1().hashCode());
		result = 37 * result
				+ (getStr3_1() == null ? 0 : this.getStr3_1().hashCode());
		result = 37 * result
				+ (getStr4_1() == null ? 0 : this.getStr4_1().hashCode());
		result = 37 * result
				+ (getStr5_1() == null ? 0 : this.getStr5_1().hashCode());
		return result;
	}

}
