package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PenyShId generated by hbm2java
 */
public class PenyShId implements java.io.Serializable {

	private String fkUslm;
	private BigDecimal kolD1;
	private BigDecimal kolD2;
	private Date dt1;
	private Date dt2;
	private BigDecimal part;
	private BigDecimal proc;
	private BigDecimal stavka;

	public PenyShId() {
	}

	public PenyShId(String fkUslm, BigDecimal kolD1, BigDecimal kolD2,
			Date dt1, Date dt2, BigDecimal part, BigDecimal proc,
			BigDecimal stavka) {
		this.fkUslm = fkUslm;
		this.kolD1 = kolD1;
		this.kolD2 = kolD2;
		this.dt1 = dt1;
		this.dt2 = dt2;
		this.part = part;
		this.proc = proc;
		this.stavka = stavka;
	}

	public String getFkUslm() {
		return this.fkUslm;
	}

	public void setFkUslm(String fkUslm) {
		this.fkUslm = fkUslm;
	}

	public BigDecimal getKolD1() {
		return this.kolD1;
	}

	public void setKolD1(BigDecimal kolD1) {
		this.kolD1 = kolD1;
	}

	public BigDecimal getKolD2() {
		return this.kolD2;
	}

	public void setKolD2(BigDecimal kolD2) {
		this.kolD2 = kolD2;
	}

	public Date getDt1() {
		return this.dt1;
	}

	public void setDt1(Date dt1) {
		this.dt1 = dt1;
	}

	public Date getDt2() {
		return this.dt2;
	}

	public void setDt2(Date dt2) {
		this.dt2 = dt2;
	}

	public BigDecimal getPart() {
		return this.part;
	}

	public void setPart(BigDecimal part) {
		this.part = part;
	}

	public BigDecimal getProc() {
		return this.proc;
	}

	public void setProc(BigDecimal proc) {
		this.proc = proc;
	}

	public BigDecimal getStavka() {
		return this.stavka;
	}

	public void setStavka(BigDecimal stavka) {
		this.stavka = stavka;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PenyShId))
			return false;
		PenyShId castOther = (PenyShId) other;

		return ((this.getFkUslm() == castOther.getFkUslm()) || (this
				.getFkUslm() != null && castOther.getFkUslm() != null && this
				.getFkUslm().equals(castOther.getFkUslm())))
				&& ((this.getKolD1() == castOther.getKolD1()) || (this
						.getKolD1() != null && castOther.getKolD1() != null && this
						.getKolD1().equals(castOther.getKolD1())))
				&& ((this.getKolD2() == castOther.getKolD2()) || (this
						.getKolD2() != null && castOther.getKolD2() != null && this
						.getKolD2().equals(castOther.getKolD2())))
				&& ((this.getDt1() == castOther.getDt1()) || (this.getDt1() != null
						&& castOther.getDt1() != null && this.getDt1().equals(
						castOther.getDt1())))
				&& ((this.getDt2() == castOther.getDt2()) || (this.getDt2() != null
						&& castOther.getDt2() != null && this.getDt2().equals(
						castOther.getDt2())))
				&& ((this.getPart() == castOther.getPart()) || (this.getPart() != null
						&& castOther.getPart() != null && this.getPart()
						.equals(castOther.getPart())))
				&& ((this.getProc() == castOther.getProc()) || (this.getProc() != null
						&& castOther.getProc() != null && this.getProc()
						.equals(castOther.getProc())))
				&& ((this.getStavka() == castOther.getStavka()) || (this
						.getStavka() != null && castOther.getStavka() != null && this
						.getStavka().equals(castOther.getStavka())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFkUslm() == null ? 0 : this.getFkUslm().hashCode());
		result = 37 * result
				+ (getKolD1() == null ? 0 : this.getKolD1().hashCode());
		result = 37 * result
				+ (getKolD2() == null ? 0 : this.getKolD2().hashCode());
		result = 37 * result
				+ (getDt1() == null ? 0 : this.getDt1().hashCode());
		result = 37 * result
				+ (getDt2() == null ? 0 : this.getDt2().hashCode());
		result = 37 * result
				+ (getPart() == null ? 0 : this.getPart().hashCode());
		result = 37 * result
				+ (getProc() == null ? 0 : this.getProc().hashCode());
		result = 37 * result
				+ (getStavka() == null ? 0 : this.getStavka().hashCode());
		return result;
	}

}
