package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * PenySh generated by hbm2java
 */
public class PenySh implements java.io.Serializable {

	private PenyShId id;

	public PenySh() {
	}

	public PenySh(PenyShId id) {
		this.id = id;
	}

	public PenyShId getId() {
		return this.id;
	}

	public void setId(PenyShId id) {
		this.id = id;
	}

}
