package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * Spul generated by hbm2java
 */
public class Spul implements java.io.Serializable {

	private SpulId id;

	public Spul() {
	}

	public Spul(SpulId id) {
		this.id = id;
	}

	public SpulId getId() {
		return this.id;
	}

	public void setId(SpulId id) {
		this.id = id;
	}

}
