package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * SpulId generated by hbm2java
 */
public class SpulId implements java.io.Serializable {

	private String kyl1;
	private String nyl;
	private String tipUl;
	private String tipGor;
	private String kodGor;
	private String gorod;
	private String dos;
	private String nylSt;

	public SpulId() {
	}

	public SpulId(String kyl1, String nyl, String tipUl, String tipGor,
			String kodGor, String gorod, String dos, String nylSt) {
		this.kyl1 = kyl1;
		this.nyl = nyl;
		this.tipUl = tipUl;
		this.tipGor = tipGor;
		this.kodGor = kodGor;
		this.gorod = gorod;
		this.dos = dos;
		this.nylSt = nylSt;
	}

	public String getKyl1() {
		return this.kyl1;
	}

	public void setKyl1(String kyl1) {
		this.kyl1 = kyl1;
	}

	public String getNyl() {
		return this.nyl;
	}

	public void setNyl(String nyl) {
		this.nyl = nyl;
	}

	public String getTipUl() {
		return this.tipUl;
	}

	public void setTipUl(String tipUl) {
		this.tipUl = tipUl;
	}

	public String getTipGor() {
		return this.tipGor;
	}

	public void setTipGor(String tipGor) {
		this.tipGor = tipGor;
	}

	public String getKodGor() {
		return this.kodGor;
	}

	public void setKodGor(String kodGor) {
		this.kodGor = kodGor;
	}

	public String getGorod() {
		return this.gorod;
	}

	public void setGorod(String gorod) {
		this.gorod = gorod;
	}

	public String getDos() {
		return this.dos;
	}

	public void setDos(String dos) {
		this.dos = dos;
	}

	public String getNylSt() {
		return this.nylSt;
	}

	public void setNylSt(String nylSt) {
		this.nylSt = nylSt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpulId))
			return false;
		SpulId castOther = (SpulId) other;

		return ((this.getKyl1() == castOther.getKyl1()) || (this.getKyl1() != null
				&& castOther.getKyl1() != null && this.getKyl1().equals(
				castOther.getKyl1())))
				&& ((this.getNyl() == castOther.getNyl()) || (this.getNyl() != null
						&& castOther.getNyl() != null && this.getNyl().equals(
						castOther.getNyl())))
				&& ((this.getTipUl() == castOther.getTipUl()) || (this
						.getTipUl() != null && castOther.getTipUl() != null && this
						.getTipUl().equals(castOther.getTipUl())))
				&& ((this.getTipGor() == castOther.getTipGor()) || (this
						.getTipGor() != null && castOther.getTipGor() != null && this
						.getTipGor().equals(castOther.getTipGor())))
				&& ((this.getKodGor() == castOther.getKodGor()) || (this
						.getKodGor() != null && castOther.getKodGor() != null && this
						.getKodGor().equals(castOther.getKodGor())))
				&& ((this.getGorod() == castOther.getGorod()) || (this
						.getGorod() != null && castOther.getGorod() != null && this
						.getGorod().equals(castOther.getGorod())))
				&& ((this.getDos() == castOther.getDos()) || (this.getDos() != null
						&& castOther.getDos() != null && this.getDos().equals(
						castOther.getDos())))
				&& ((this.getNylSt() == castOther.getNylSt()) || (this
						.getNylSt() != null && castOther.getNylSt() != null && this
						.getNylSt().equals(castOther.getNylSt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKyl1() == null ? 0 : this.getKyl1().hashCode());
		result = 37 * result
				+ (getNyl() == null ? 0 : this.getNyl().hashCode());
		result = 37 * result
				+ (getTipUl() == null ? 0 : this.getTipUl().hashCode());
		result = 37 * result
				+ (getTipGor() == null ? 0 : this.getTipGor().hashCode());
		result = 37 * result
				+ (getKodGor() == null ? 0 : this.getKodGor().hashCode());
		result = 37 * result
				+ (getGorod() == null ? 0 : this.getGorod().hashCode());
		result = 37 * result
				+ (getDos() == null ? 0 : this.getDos().hashCode());
		result = 37 * result
				+ (getNylSt() == null ? 0 : this.getNylSt().hashCode());
		return result;
	}

}
