package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * SwxNpg generated by hbm2java
 */
public class SwxNpg implements java.io.Serializable {

	private SwxNpgId id;

	public SwxNpg() {
	}

	public SwxNpg(SwxNpgId id) {
		this.id = id;
	}

	public SwxNpgId getId() {
		return this.id;
	}

	public void setId(SwxNpgId id) {
		this.id = id;
	}

}
