package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * TableLong generated by hbm2java
 */
public class TableLong implements java.io.Serializable {

	private TableLongId id;

	public TableLong() {
	}

	public TableLong(TableLongId id) {
		this.id = id;
	}

	public TableLongId getId() {
		return this.id;
	}

	public void setId(TableLongId id) {
		this.id = id;
	}

}
