package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.sql.Clob;

/**
 * TableLongId generated by hbm2java
 */
public class TableLongId implements java.io.Serializable {

	private Blob sql;
	private Clob clobSql;

	public TableLongId() {
	}

	public TableLongId(Blob sql, Clob clobSql) {
		this.sql = sql;
		this.clobSql = clobSql;
	}

	public Blob getSql() {
		return this.sql;
	}

	public void setSql(Blob sql) {
		this.sql = sql;
	}

	public Clob getClobSql() {
		return this.clobSql;
	}

	public void setClobSql(Clob clobSql) {
		this.clobSql = clobSql;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TableLongId))
			return false;
		TableLongId castOther = (TableLongId) other;

		return ((this.getSql() == castOther.getSql()) || (this.getSql() != null
				&& castOther.getSql() != null && this.getSql().equals(
				castOther.getSql())))
				&& ((this.getClobSql() == castOther.getClobSql()) || (this
						.getClobSql() != null && castOther.getClobSql() != null && this
						.getClobSql().equals(castOther.getClobSql())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSql() == null ? 0 : this.getSql().hashCode());
		result = 37 * result
				+ (getClobSql() == null ? 0 : this.getClobSql().hashCode());
		return result;
	}

}
