package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TempAFlowDebId generated by hbm2java
 */
public class TempAFlowDebId implements java.io.Serializable {

	private String lsk;
	private String fkUsl;
	private BigDecimal fkType;
	private BigDecimal summa;
	private BigDecimal fkOrg;
	private String dopl;
	private String fkOper;
	private Date dt1;
	private BigDecimal summap;
	private String mg;
	private BigDecimal n1;
	private BigDecimal n2;
	private BigDecimal n3;
	private BigDecimal n4;
	private BigDecimal n5;
	private BigDecimal n6;
	private String fkUslm;
	private Date dt2;

	public TempAFlowDebId() {
	}

	public TempAFlowDebId(String lsk, String fkUsl, BigDecimal fkType,
			BigDecimal summa, BigDecimal fkOrg, String dopl, String fkOper,
			Date dt1, BigDecimal summap, String mg, BigDecimal n1,
			BigDecimal n2, BigDecimal n3, BigDecimal n4, BigDecimal n5,
			BigDecimal n6, String fkUslm, Date dt2) {
		this.lsk = lsk;
		this.fkUsl = fkUsl;
		this.fkType = fkType;
		this.summa = summa;
		this.fkOrg = fkOrg;
		this.dopl = dopl;
		this.fkOper = fkOper;
		this.dt1 = dt1;
		this.summap = summap;
		this.mg = mg;
		this.n1 = n1;
		this.n2 = n2;
		this.n3 = n3;
		this.n4 = n4;
		this.n5 = n5;
		this.n6 = n6;
		this.fkUslm = fkUslm;
		this.dt2 = dt2;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public String getFkUsl() {
		return this.fkUsl;
	}

	public void setFkUsl(String fkUsl) {
		this.fkUsl = fkUsl;
	}

	public BigDecimal getFkType() {
		return this.fkType;
	}

	public void setFkType(BigDecimal fkType) {
		this.fkType = fkType;
	}

	public BigDecimal getSumma() {
		return this.summa;
	}

	public void setSumma(BigDecimal summa) {
		this.summa = summa;
	}

	public BigDecimal getFkOrg() {
		return this.fkOrg;
	}

	public void setFkOrg(BigDecimal fkOrg) {
		this.fkOrg = fkOrg;
	}

	public String getDopl() {
		return this.dopl;
	}

	public void setDopl(String dopl) {
		this.dopl = dopl;
	}

	public String getFkOper() {
		return this.fkOper;
	}

	public void setFkOper(String fkOper) {
		this.fkOper = fkOper;
	}

	public Date getDt1() {
		return this.dt1;
	}

	public void setDt1(Date dt1) {
		this.dt1 = dt1;
	}

	public BigDecimal getSummap() {
		return this.summap;
	}

	public void setSummap(BigDecimal summap) {
		this.summap = summap;
	}

	public String getMg() {
		return this.mg;
	}

	public void setMg(String mg) {
		this.mg = mg;
	}

	public BigDecimal getN1() {
		return this.n1;
	}

	public void setN1(BigDecimal n1) {
		this.n1 = n1;
	}

	public BigDecimal getN2() {
		return this.n2;
	}

	public void setN2(BigDecimal n2) {
		this.n2 = n2;
	}

	public BigDecimal getN3() {
		return this.n3;
	}

	public void setN3(BigDecimal n3) {
		this.n3 = n3;
	}

	public BigDecimal getN4() {
		return this.n4;
	}

	public void setN4(BigDecimal n4) {
		this.n4 = n4;
	}

	public BigDecimal getN5() {
		return this.n5;
	}

	public void setN5(BigDecimal n5) {
		this.n5 = n5;
	}

	public BigDecimal getN6() {
		return this.n6;
	}

	public void setN6(BigDecimal n6) {
		this.n6 = n6;
	}

	public String getFkUslm() {
		return this.fkUslm;
	}

	public void setFkUslm(String fkUslm) {
		this.fkUslm = fkUslm;
	}

	public Date getDt2() {
		return this.dt2;
	}

	public void setDt2(Date dt2) {
		this.dt2 = dt2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TempAFlowDebId))
			return false;
		TempAFlowDebId castOther = (TempAFlowDebId) other;

		return ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
				&& castOther.getLsk() != null && this.getLsk().equals(
				castOther.getLsk())))
				&& ((this.getFkUsl() == castOther.getFkUsl()) || (this
						.getFkUsl() != null && castOther.getFkUsl() != null && this
						.getFkUsl().equals(castOther.getFkUsl())))
				&& ((this.getFkType() == castOther.getFkType()) || (this
						.getFkType() != null && castOther.getFkType() != null && this
						.getFkType().equals(castOther.getFkType())))
				&& ((this.getSumma() == castOther.getSumma()) || (this
						.getSumma() != null && castOther.getSumma() != null && this
						.getSumma().equals(castOther.getSumma())))
				&& ((this.getFkOrg() == castOther.getFkOrg()) || (this
						.getFkOrg() != null && castOther.getFkOrg() != null && this
						.getFkOrg().equals(castOther.getFkOrg())))
				&& ((this.getDopl() == castOther.getDopl()) || (this.getDopl() != null
						&& castOther.getDopl() != null && this.getDopl()
						.equals(castOther.getDopl())))
				&& ((this.getFkOper() == castOther.getFkOper()) || (this
						.getFkOper() != null && castOther.getFkOper() != null && this
						.getFkOper().equals(castOther.getFkOper())))
				&& ((this.getDt1() == castOther.getDt1()) || (this.getDt1() != null
						&& castOther.getDt1() != null && this.getDt1().equals(
						castOther.getDt1())))
				&& ((this.getSummap() == castOther.getSummap()) || (this
						.getSummap() != null && castOther.getSummap() != null && this
						.getSummap().equals(castOther.getSummap())))
				&& ((this.getMg() == castOther.getMg()) || (this.getMg() != null
						&& castOther.getMg() != null && this.getMg().equals(
						castOther.getMg())))
				&& ((this.getN1() == castOther.getN1()) || (this.getN1() != null
						&& castOther.getN1() != null && this.getN1().equals(
						castOther.getN1())))
				&& ((this.getN2() == castOther.getN2()) || (this.getN2() != null
						&& castOther.getN2() != null && this.getN2().equals(
						castOther.getN2())))
				&& ((this.getN3() == castOther.getN3()) || (this.getN3() != null
						&& castOther.getN3() != null && this.getN3().equals(
						castOther.getN3())))
				&& ((this.getN4() == castOther.getN4()) || (this.getN4() != null
						&& castOther.getN4() != null && this.getN4().equals(
						castOther.getN4())))
				&& ((this.getN5() == castOther.getN5()) || (this.getN5() != null
						&& castOther.getN5() != null && this.getN5().equals(
						castOther.getN5())))
				&& ((this.getN6() == castOther.getN6()) || (this.getN6() != null
						&& castOther.getN6() != null && this.getN6().equals(
						castOther.getN6())))
				&& ((this.getFkUslm() == castOther.getFkUslm()) || (this
						.getFkUslm() != null && castOther.getFkUslm() != null && this
						.getFkUslm().equals(castOther.getFkUslm())))
				&& ((this.getDt2() == castOther.getDt2()) || (this.getDt2() != null
						&& castOther.getDt2() != null && this.getDt2().equals(
						castOther.getDt2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getFkUsl() == null ? 0 : this.getFkUsl().hashCode());
		result = 37 * result
				+ (getFkType() == null ? 0 : this.getFkType().hashCode());
		result = 37 * result
				+ (getSumma() == null ? 0 : this.getSumma().hashCode());
		result = 37 * result
				+ (getFkOrg() == null ? 0 : this.getFkOrg().hashCode());
		result = 37 * result
				+ (getDopl() == null ? 0 : this.getDopl().hashCode());
		result = 37 * result
				+ (getFkOper() == null ? 0 : this.getFkOper().hashCode());
		result = 37 * result
				+ (getDt1() == null ? 0 : this.getDt1().hashCode());
		result = 37 * result
				+ (getSummap() == null ? 0 : this.getSummap().hashCode());
		result = 37 * result + (getMg() == null ? 0 : this.getMg().hashCode());
		result = 37 * result + (getN1() == null ? 0 : this.getN1().hashCode());
		result = 37 * result + (getN2() == null ? 0 : this.getN2().hashCode());
		result = 37 * result + (getN3() == null ? 0 : this.getN3().hashCode());
		result = 37 * result + (getN4() == null ? 0 : this.getN4().hashCode());
		result = 37 * result + (getN5() == null ? 0 : this.getN5().hashCode());
		result = 37 * result + (getN6() == null ? 0 : this.getN6().hashCode());
		result = 37 * result
				+ (getFkUslm() == null ? 0 : this.getFkUslm().hashCode());
		result = 37 * result
				+ (getDt2() == null ? 0 : this.getDt2().hashCode());
		return result;
	}

}
