package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * TempLskKw generated by hbm2java
 */
public class TempLskKw implements java.io.Serializable {

	private TempLskKwId id;

	public TempLskKw() {
	}

	public TempLskKw(TempLskKwId id) {
		this.id = id;
	}

	public TempLskKwId getId() {
		return this.id;
	}

	public void setId(TempLskKwId id) {
		this.id = id;
	}

}
