package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * TempPar generated by hbm2java
 */
public class TempPar implements java.io.Serializable {

	private TempParId id;

	public TempPar() {
	}

	public TempPar(TempParId id) {
		this.id = id;
	}

	public TempParId getId() {
		return this.id;
	}

	public void setId(TempParId id) {
		this.id = id;
	}

}
