package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TempLskKwId generated by hbm2java
 */
public class TempLskKwId implements java.io.Serializable {

	private BigDecimal rn;
	private String lsk;
	private String idJku;
	private String typLsk;
	private String nanimat;
	private String fio;
	private String fioIm;
	private String fioOt;
	private String snils;
	private String docType;
	private String numDok;
	private String serDok;
	private String DDok;
	private String ogrn;
	private String kpp;
	private BigDecimal opl;
	private BigDecimal ppl;
	private BigDecimal otpl;
	private Short kolPr;
	private String adr;
	private String kodFias;
	private String nkw;
	private String nkomn;
	private String gisLsk;
	private BigDecimal dolya;
	private String gisUflatCd;

	public TempLskKwId() {
	}

	public TempLskKwId(BigDecimal rn, String lsk, String idJku, String typLsk,
			String nanimat, String fio, String fioIm, String fioOt,
			String snils, String docType, String numDok, String serDok,
			String DDok, String ogrn, String kpp, BigDecimal opl,
			BigDecimal ppl, BigDecimal otpl, Short kolPr, String adr,
			String kodFias, String nkw, String nkomn, String gisLsk,
			BigDecimal dolya, String gisUflatCd) {
		this.rn = rn;
		this.lsk = lsk;
		this.idJku = idJku;
		this.typLsk = typLsk;
		this.nanimat = nanimat;
		this.fio = fio;
		this.fioIm = fioIm;
		this.fioOt = fioOt;
		this.snils = snils;
		this.docType = docType;
		this.numDok = numDok;
		this.serDok = serDok;
		this.DDok = DDok;
		this.ogrn = ogrn;
		this.kpp = kpp;
		this.opl = opl;
		this.ppl = ppl;
		this.otpl = otpl;
		this.kolPr = kolPr;
		this.adr = adr;
		this.kodFias = kodFias;
		this.nkw = nkw;
		this.nkomn = nkomn;
		this.gisLsk = gisLsk;
		this.dolya = dolya;
		this.gisUflatCd = gisUflatCd;
	}

	public BigDecimal getRn() {
		return this.rn;
	}

	public void setRn(BigDecimal rn) {
		this.rn = rn;
	}

	public String getLsk() {
		return this.lsk;
	}

	public void setLsk(String lsk) {
		this.lsk = lsk;
	}

	public String getIdJku() {
		return this.idJku;
	}

	public void setIdJku(String idJku) {
		this.idJku = idJku;
	}

	public String getTypLsk() {
		return this.typLsk;
	}

	public void setTypLsk(String typLsk) {
		this.typLsk = typLsk;
	}

	public String getNanimat() {
		return this.nanimat;
	}

	public void setNanimat(String nanimat) {
		this.nanimat = nanimat;
	}

	public String getFio() {
		return this.fio;
	}

	public void setFio(String fio) {
		this.fio = fio;
	}

	public String getFioIm() {
		return this.fioIm;
	}

	public void setFioIm(String fioIm) {
		this.fioIm = fioIm;
	}

	public String getFioOt() {
		return this.fioOt;
	}

	public void setFioOt(String fioOt) {
		this.fioOt = fioOt;
	}

	public String getSnils() {
		return this.snils;
	}

	public void setSnils(String snils) {
		this.snils = snils;
	}

	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public String getNumDok() {
		return this.numDok;
	}

	public void setNumDok(String numDok) {
		this.numDok = numDok;
	}

	public String getSerDok() {
		return this.serDok;
	}

	public void setSerDok(String serDok) {
		this.serDok = serDok;
	}

	public String getDDok() {
		return this.DDok;
	}

	public void setDDok(String DDok) {
		this.DDok = DDok;
	}

	public String getOgrn() {
		return this.ogrn;
	}

	public void setOgrn(String ogrn) {
		this.ogrn = ogrn;
	}

	public String getKpp() {
		return this.kpp;
	}

	public void setKpp(String kpp) {
		this.kpp = kpp;
	}

	public BigDecimal getOpl() {
		return this.opl;
	}

	public void setOpl(BigDecimal opl) {
		this.opl = opl;
	}

	public BigDecimal getPpl() {
		return this.ppl;
	}

	public void setPpl(BigDecimal ppl) {
		this.ppl = ppl;
	}

	public BigDecimal getOtpl() {
		return this.otpl;
	}

	public void setOtpl(BigDecimal otpl) {
		this.otpl = otpl;
	}

	public Short getKolPr() {
		return this.kolPr;
	}

	public void setKolPr(Short kolPr) {
		this.kolPr = kolPr;
	}

	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	public String getKodFias() {
		return this.kodFias;
	}

	public void setKodFias(String kodFias) {
		this.kodFias = kodFias;
	}

	public String getNkw() {
		return this.nkw;
	}

	public void setNkw(String nkw) {
		this.nkw = nkw;
	}

	public String getNkomn() {
		return this.nkomn;
	}

	public void setNkomn(String nkomn) {
		this.nkomn = nkomn;
	}

	public String getGisLsk() {
		return this.gisLsk;
	}

	public void setGisLsk(String gisLsk) {
		this.gisLsk = gisLsk;
	}

	public BigDecimal getDolya() {
		return this.dolya;
	}

	public void setDolya(BigDecimal dolya) {
		this.dolya = dolya;
	}

	public String getGisUflatCd() {
		return this.gisUflatCd;
	}

	public void setGisUflatCd(String gisUflatCd) {
		this.gisUflatCd = gisUflatCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TempLskKwId))
			return false;
		TempLskKwId castOther = (TempLskKwId) other;

		return ((this.getRn() == castOther.getRn()) || (this.getRn() != null
				&& castOther.getRn() != null && this.getRn().equals(
				castOther.getRn())))
				&& ((this.getLsk() == castOther.getLsk()) || (this.getLsk() != null
						&& castOther.getLsk() != null && this.getLsk().equals(
						castOther.getLsk())))
				&& ((this.getIdJku() == castOther.getIdJku()) || (this
						.getIdJku() != null && castOther.getIdJku() != null && this
						.getIdJku().equals(castOther.getIdJku())))
				&& ((this.getTypLsk() == castOther.getTypLsk()) || (this
						.getTypLsk() != null && castOther.getTypLsk() != null && this
						.getTypLsk().equals(castOther.getTypLsk())))
				&& ((this.getNanimat() == castOther.getNanimat()) || (this
						.getNanimat() != null && castOther.getNanimat() != null && this
						.getNanimat().equals(castOther.getNanimat())))
				&& ((this.getFio() == castOther.getFio()) || (this.getFio() != null
						&& castOther.getFio() != null && this.getFio().equals(
						castOther.getFio())))
				&& ((this.getFioIm() == castOther.getFioIm()) || (this
						.getFioIm() != null && castOther.getFioIm() != null && this
						.getFioIm().equals(castOther.getFioIm())))
				&& ((this.getFioOt() == castOther.getFioOt()) || (this
						.getFioOt() != null && castOther.getFioOt() != null && this
						.getFioOt().equals(castOther.getFioOt())))
				&& ((this.getSnils() == castOther.getSnils()) || (this
						.getSnils() != null && castOther.getSnils() != null && this
						.getSnils().equals(castOther.getSnils())))
				&& ((this.getDocType() == castOther.getDocType()) || (this
						.getDocType() != null && castOther.getDocType() != null && this
						.getDocType().equals(castOther.getDocType())))
				&& ((this.getNumDok() == castOther.getNumDok()) || (this
						.getNumDok() != null && castOther.getNumDok() != null && this
						.getNumDok().equals(castOther.getNumDok())))
				&& ((this.getSerDok() == castOther.getSerDok()) || (this
						.getSerDok() != null && castOther.getSerDok() != null && this
						.getSerDok().equals(castOther.getSerDok())))
				&& ((this.getDDok() == castOther.getDDok()) || (this.getDDok() != null
						&& castOther.getDDok() != null && this.getDDok()
						.equals(castOther.getDDok())))
				&& ((this.getOgrn() == castOther.getOgrn()) || (this.getOgrn() != null
						&& castOther.getOgrn() != null && this.getOgrn()
						.equals(castOther.getOgrn())))
				&& ((this.getKpp() == castOther.getKpp()) || (this.getKpp() != null
						&& castOther.getKpp() != null && this.getKpp().equals(
						castOther.getKpp())))
				&& ((this.getOpl() == castOther.getOpl()) || (this.getOpl() != null
						&& castOther.getOpl() != null && this.getOpl().equals(
						castOther.getOpl())))
				&& ((this.getPpl() == castOther.getPpl()) || (this.getPpl() != null
						&& castOther.getPpl() != null && this.getPpl().equals(
						castOther.getPpl())))
				&& ((this.getOtpl() == castOther.getOtpl()) || (this.getOtpl() != null
						&& castOther.getOtpl() != null && this.getOtpl()
						.equals(castOther.getOtpl())))
				&& ((this.getKolPr() == castOther.getKolPr()) || (this
						.getKolPr() != null && castOther.getKolPr() != null && this
						.getKolPr().equals(castOther.getKolPr())))
				&& ((this.getAdr() == castOther.getAdr()) || (this.getAdr() != null
						&& castOther.getAdr() != null && this.getAdr().equals(
						castOther.getAdr())))
				&& ((this.getKodFias() == castOther.getKodFias()) || (this
						.getKodFias() != null && castOther.getKodFias() != null && this
						.getKodFias().equals(castOther.getKodFias())))
				&& ((this.getNkw() == castOther.getNkw()) || (this.getNkw() != null
						&& castOther.getNkw() != null && this.getNkw().equals(
						castOther.getNkw())))
				&& ((this.getNkomn() == castOther.getNkomn()) || (this
						.getNkomn() != null && castOther.getNkomn() != null && this
						.getNkomn().equals(castOther.getNkomn())))
				&& ((this.getGisLsk() == castOther.getGisLsk()) || (this
						.getGisLsk() != null && castOther.getGisLsk() != null && this
						.getGisLsk().equals(castOther.getGisLsk())))
				&& ((this.getDolya() == castOther.getDolya()) || (this
						.getDolya() != null && castOther.getDolya() != null && this
						.getDolya().equals(castOther.getDolya())))
				&& ((this.getGisUflatCd() == castOther.getGisUflatCd()) || (this
						.getGisUflatCd() != null
						&& castOther.getGisUflatCd() != null && this
						.getGisUflatCd().equals(castOther.getGisUflatCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRn() == null ? 0 : this.getRn().hashCode());
		result = 37 * result
				+ (getLsk() == null ? 0 : this.getLsk().hashCode());
		result = 37 * result
				+ (getIdJku() == null ? 0 : this.getIdJku().hashCode());
		result = 37 * result
				+ (getTypLsk() == null ? 0 : this.getTypLsk().hashCode());
		result = 37 * result
				+ (getNanimat() == null ? 0 : this.getNanimat().hashCode());
		result = 37 * result
				+ (getFio() == null ? 0 : this.getFio().hashCode());
		result = 37 * result
				+ (getFioIm() == null ? 0 : this.getFioIm().hashCode());
		result = 37 * result
				+ (getFioOt() == null ? 0 : this.getFioOt().hashCode());
		result = 37 * result
				+ (getSnils() == null ? 0 : this.getSnils().hashCode());
		result = 37 * result
				+ (getDocType() == null ? 0 : this.getDocType().hashCode());
		result = 37 * result
				+ (getNumDok() == null ? 0 : this.getNumDok().hashCode());
		result = 37 * result
				+ (getSerDok() == null ? 0 : this.getSerDok().hashCode());
		result = 37 * result
				+ (getDDok() == null ? 0 : this.getDDok().hashCode());
		result = 37 * result
				+ (getOgrn() == null ? 0 : this.getOgrn().hashCode());
		result = 37 * result
				+ (getKpp() == null ? 0 : this.getKpp().hashCode());
		result = 37 * result
				+ (getOpl() == null ? 0 : this.getOpl().hashCode());
		result = 37 * result
				+ (getPpl() == null ? 0 : this.getPpl().hashCode());
		result = 37 * result
				+ (getOtpl() == null ? 0 : this.getOtpl().hashCode());
		result = 37 * result
				+ (getKolPr() == null ? 0 : this.getKolPr().hashCode());
		result = 37 * result
				+ (getAdr() == null ? 0 : this.getAdr().hashCode());
		result = 37 * result
				+ (getKodFias() == null ? 0 : this.getKodFias().hashCode());
		result = 37 * result
				+ (getNkw() == null ? 0 : this.getNkw().hashCode());
		result = 37 * result
				+ (getNkomn() == null ? 0 : this.getNkomn().hashCode());
		result = 37 * result
				+ (getGisLsk() == null ? 0 : this.getGisLsk().hashCode());
		result = 37 * result
				+ (getDolya() == null ? 0 : this.getDolya().hashCode());
		result = 37
				* result
				+ (getGisUflatCd() == null ? 0 : this.getGisUflatCd()
						.hashCode());
		return result;
	}

}
