package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * TempAFlowDeb generated by hbm2java
 */
public class TempAFlowDeb implements java.io.Serializable {

	private TempAFlowDebId id;

	public TempAFlowDeb() {
	}

	public TempAFlowDeb(TempAFlowDebId id) {
		this.id = id;
	}

	public TempAFlowDebId getId() {
		return this.id;
	}

	public void setId(TempAFlowDebId id) {
		this.id = id;
	}

}
