package test1;

// Generated 21.10.2016 14:56:01 by Hibernate Tools 3.4.0.CR1

/**
 * TrIrbSoap generated by hbm2java
 */
public class TrIrbSoap implements java.io.Serializable {

	private TrIrbSoapId id;

	public TrIrbSoap() {
	}

	public TrIrbSoap(TrIrbSoapId id) {
		this.id = id;
	}

	public TrIrbSoapId getId() {
		return this.id;
	}

	public void setId(TrIrbSoapId id) {
		this.id = id;
	}

}
