
package ru.gosuslugi.dom.schema.integration.inspection_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Асинхронный сервис работы с планами проверок и проверками
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InspectionServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection-service-async/", wsdlLocation = "file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.0.0.3/hcs_wsdl_xsd_v.11.0.0.3/inspection/hcs-inspection-service-async.wsdl")
public class InspectionServiceAsync
    extends Service
{

    private final static URL INSPECTIONSERVICEASYNC_WSDL_LOCATION;
    private final static WebServiceException INSPECTIONSERVICEASYNC_EXCEPTION;
    private final static QName INSPECTIONSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/inspection-service-async/", "InspectionServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.0.0.3/hcs_wsdl_xsd_v.11.0.0.3/inspection/hcs-inspection-service-async.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSPECTIONSERVICEASYNC_WSDL_LOCATION = url;
        INSPECTIONSERVICEASYNC_EXCEPTION = e;
    }

    public InspectionServiceAsync() {
        super(__getWsdlLocation(), INSPECTIONSERVICEASYNC_QNAME);
    }

    public InspectionServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSPECTIONSERVICEASYNC_QNAME, features);
    }

    public InspectionServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, INSPECTIONSERVICEASYNC_QNAME);
    }

    public InspectionServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSPECTIONSERVICEASYNC_QNAME, features);
    }

    public InspectionServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InspectionServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InspectionPortsTypeAsync
     */
    @WebEndpoint(name = "InspectionPortAsync")
    public InspectionPortsTypeAsync getInspectionPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/inspection-service-async/", "InspectionPortAsync"), InspectionPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InspectionPortsTypeAsync
     */
    @WebEndpoint(name = "InspectionPortAsync")
    public InspectionPortsTypeAsync getInspectionPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/inspection-service-async/", "InspectionPortAsync"), InspectionPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSPECTIONSERVICEASYNC_EXCEPTION!= null) {
            throw INSPECTIONSERVICEASYNC_EXCEPTION;
        }
        return INSPECTIONSERVICEASYNC_WSDL_LOCATION;
    }

}
