
package ru.gosuslugi.dom.schema.integration.inspection_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ExportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ExportInspectionPlansRequest;
import ru.gosuslugi.dom.schema.integration.inspection.GetStateResult;
import ru.gosuslugi.dom.schema.integration.inspection.ImportExaminationsRequest;
import ru.gosuslugi.dom.schema.integration.inspection.ImportInspectionPlanRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InspectionPortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.inspection.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface InspectionPortsTypeAsync {


    /**
     * ВИ_ПИЖФ_ИПП. Импорт плана проверок.
     * 
     * @param importInspectionPlanRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importInspectionPlan")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importInspectionPlan(
        @WebParam(name = "importInspectionPlanRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "importInspectionPlanRequest")
        ImportInspectionPlanRequest importInspectionPlanRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭПП. Экспорт плана проверок.
     * 
     * @param exportInspectionPlansRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportInspectionPlans")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportInspectionPlans(
        @WebParam(name = "exportInspectionPlansRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "exportInspectionPlansRequest")
        ExportInspectionPlansRequest exportInspectionPlansRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ИП. Импорт проверок.
     * 
     * @param importExaminationsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importExaminations")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importExaminations(
        @WebParam(name = "importExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "importExaminationsRequest")
        ImportExaminationsRequest importExaminationsRequest)
        throws Fault
    ;

    /**
     * ВИ_ПИЖФ_ЭП. Экспорт проверок.
     * 
     * @param exportExaminationsRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportExaminations")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportExaminations(
        @WebParam(name = "exportExaminationsRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "exportExaminationsRequest")
        ExportExaminationsRequest exportExaminationsRequest)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.inspection.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/inspection/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

}
