
package ru.gosuslugi.dom.schema.integration.services_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicesServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/services-service-async/", wsdlLocation = "file:/C:/work/GIS_MUP/GIS11_5/hcs_wsdl_xsd_v.11.0.0.5/services/hcs-services-service-async.wsdl")
public class ServicesServiceAsync
    extends Service
{

    private final static URL SERVICESSERVICEASYNC_WSDL_LOCATION;
    private final static WebServiceException SERVICESSERVICEASYNC_EXCEPTION;
    private final static QName SERVICESSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/services-service-async/", "ServicesServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/GIS11_5/hcs_wsdl_xsd_v.11.0.0.5/services/hcs-services-service-async.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESSERVICEASYNC_WSDL_LOCATION = url;
        SERVICESSERVICEASYNC_EXCEPTION = e;
    }

    public ServicesServiceAsync() {
        super(__getWsdlLocation(), SERVICESSERVICEASYNC_QNAME);
    }

    public ServicesServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESSERVICEASYNC_QNAME, features);
    }

    public ServicesServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, SERVICESSERVICEASYNC_QNAME);
    }

    public ServicesServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESSERVICEASYNC_QNAME, features);
    }

    public ServicesServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicesPortsTypeAsync
     */
    @WebEndpoint(name = "defaultPort")
    public ServicesPortsTypeAsync getDefaultPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/services-service-async/", "defaultPort"), ServicesPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesPortsTypeAsync
     */
    @WebEndpoint(name = "defaultPort")
    public ServicesPortsTypeAsync getDefaultPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/services-service-async/", "defaultPort"), ServicesPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESSERVICEASYNC_EXCEPTION!= null) {
            throw SERVICESSERVICEASYNC_EXCEPTION;
        }
        return SERVICESSERVICEASYNC_WSDL_LOCATION;
    }

}
