
package ru.gosuslugi.dom.schema.integration.nsi_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.ImportResult;
import ru.gosuslugi.dom.schema.integration.nsi.ExportDataProviderNsiItemRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ExportNsiItemResult;
import ru.gosuslugi.dom.schema.integration.nsi.ImportAdditionalServicesRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportMunicipalServicesRequest;
import ru.gosuslugi.dom.schema.integration.nsi.ImportOrganizationWorksRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NsiPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface NsiPortsType {


    /**
     * ВИ_НСИ_ИДС_1. Импортировать данные справочника 1 "Дополнительные услуги".
     * 
     * @param importAdditionalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importAdditionalServices")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importAdditionalServicesResult")
    public ImportResult importAdditionalServices(
        @WebParam(name = "importAdditionalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importAdditionalServicesRequest")
        ImportAdditionalServicesRequest importAdditionalServicesRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_51. Импортировать данные справочника 51 "Коммунальные услуги".
     * 
     * @param importMunicipalServicesRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importMunicipalServices")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importMunicipalServicesResult")
    public ImportResult importMunicipalServices(
        @WebParam(name = "importMunicipalServicesRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importMunicipalServicesRequest")
        ImportMunicipalServicesRequest importMunicipalServicesRequest)
        throws Fault
    ;

    /**
     * ВИ_НСИ_ИДС_59. Импортировать данные справочника 59 "Работы и услуги организации".
     * 
     * @param importOrganizationWorksRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importOrganizationWorks")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importOrganizationWorksResult")
    public ImportResult importOrganizationWorks(
        @WebParam(name = "importOrganizationWorksRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "importOrganizationWorksRequest")
        ImportOrganizationWorksRequest importOrganizationWorksRequest)
        throws Fault
    ;

    /**
     * Экспортировать данные справочников поставщика информации  (1,51,59)
     * 
     * @param exportDataProviderNsiItemRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.nsi.ExportNsiItemResult
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDataProviderNsiItem")
    @WebResult(name = "exportNsiItemResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "exportDataProviderNsiItemResult")
    public ExportNsiItemResult exportDataProviderNsiItem(
        @WebParam(name = "exportDataProviderNsiItemRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/nsi/", partName = "exportDataProviderNsiItemRequest")
        ExportDataProviderNsiItemRequest exportDataProviderNsiItemRequest)
        throws Fault
    ;

}
