
package ru.gosuslugi.dom.schema.integration.payment_service_async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentsServiceAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/payment-service-async/", wsdlLocation = "file:/C:/work/GIS_MUP/GIS11_5/hcs_wsdl_xsd_v.11.0.0.5/payment/hcs-payment-service-async.wsdl")
public class PaymentsServiceAsync
    extends Service
{

    private final static URL PAYMENTSSERVICEASYNC_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSSERVICEASYNC_EXCEPTION;
    private final static QName PAYMENTSSERVICEASYNC_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/payment-service-async/", "PaymentsServiceAsync");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/GIS11_5/hcs_wsdl_xsd_v.11.0.0.5/payment/hcs-payment-service-async.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSSERVICEASYNC_WSDL_LOCATION = url;
        PAYMENTSSERVICEASYNC_EXCEPTION = e;
    }

    public PaymentsServiceAsync() {
        super(__getWsdlLocation(), PAYMENTSSERVICEASYNC_QNAME);
    }

    public PaymentsServiceAsync(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSSERVICEASYNC_QNAME, features);
    }

    public PaymentsServiceAsync(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSSERVICEASYNC_QNAME);
    }

    public PaymentsServiceAsync(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSSERVICEASYNC_QNAME, features);
    }

    public PaymentsServiceAsync(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentsServiceAsync(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentPortsTypeAsync
     */
    @WebEndpoint(name = "PaymentPortAsync")
    public PaymentPortsTypeAsync getPaymentPortAsync() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/payment-service-async/", "PaymentPortAsync"), PaymentPortsTypeAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentPortsTypeAsync
     */
    @WebEndpoint(name = "PaymentPortAsync")
    public PaymentPortsTypeAsync getPaymentPortAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/payment-service-async/", "PaymentPortAsync"), PaymentPortsTypeAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSSERVICEASYNC_EXCEPTION!= null) {
            throw PAYMENTSSERVICEASYNC_EXCEPTION;
        }
        return PAYMENTSSERVICEASYNC_WSDL_LOCATION;
    }

}
