
package ru.gosuslugi.dom.schema.integration.infrastructure_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.infrastructure.ExportOKIRequest;
import ru.gosuslugi.dom.schema.integration.infrastructure.GetStateResult;
import ru.gosuslugi.dom.schema.integration.infrastructure.ImportOKIRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfrastructurePortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/infrastructure-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.infrastructure.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class
})
public interface InfrastructurePortsTypeAsync {


    /**
     * Импорт информации об ОКИ
     * 
     * @param importOKIRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:importOKI")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest importOKI(
        @WebParam(name = "importOKIRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/infrastructure/", partName = "importOKIRequest")
        ImportOKIRequest importOKIRequest)
        throws Fault
    ;

    /**
     * Экспорт списка ОКИ 
     * 
     * @param exportOKIRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportOKI")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportOKI(
        @WebParam(name = "exportOKIRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/infrastructure/", partName = "exportOKIRequest")
        ExportOKIRequest exportOKIRequest)
        throws Fault
    ;

    /**
     * Получить статус запроса
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.infrastructure.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/infrastructure/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

}
