
package ru.gosuslugi.dom.schema.integration.signature_test_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Сервис тестирования ЭП интеграции
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SignatureTestService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/signature-test-service/", wsdlLocation = "file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.0.0.3/hcs_wsdl_xsd_v.11.0.0.3/signature-test/hcs-signature-test-service.wsdl")
public class SignatureTestService
    extends Service
{

    private final static URL SIGNATURETESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIGNATURETESTSERVICE_EXCEPTION;
    private final static QName SIGNATURETESTSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/signature-test-service/", "SignatureTestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.0.0.3/hcs_wsdl_xsd_v.11.0.0.3/signature-test/hcs-signature-test-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIGNATURETESTSERVICE_WSDL_LOCATION = url;
        SIGNATURETESTSERVICE_EXCEPTION = e;
    }

    public SignatureTestService() {
        super(__getWsdlLocation(), SIGNATURETESTSERVICE_QNAME);
    }

    public SignatureTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIGNATURETESTSERVICE_QNAME, features);
    }

    public SignatureTestService(URL wsdlLocation) {
        super(wsdlLocation, SIGNATURETESTSERVICE_QNAME);
    }

    public SignatureTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIGNATURETESTSERVICE_QNAME, features);
    }

    public SignatureTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SignatureTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SignatureTestPortType
     */
    @WebEndpoint(name = "SignatureTestPort")
    public SignatureTestPortType getSignatureTestPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/signature-test-service/", "SignatureTestPort"), SignatureTestPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SignatureTestPortType
     */
    @WebEndpoint(name = "SignatureTestPort")
    public SignatureTestPortType getSignatureTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/signature-test-service/", "SignatureTestPort"), SignatureTestPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIGNATURETESTSERVICE_EXCEPTION!= null) {
            throw SIGNATURETESTSERVICE_EXCEPTION;
        }
        return SIGNATURETESTSERVICE_WSDL_LOCATION;
    }

}
