
package ru.gosuslugi.dom.schema.integration.signature_test_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.signature_test.TestSignatureRequest;
import ru.gosuslugi.dom.schema.integration.signature_test.TestSignatureResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SignatureTestPortType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/signature-test-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.signature_test.ObjectFactory.class
})
public interface SignatureTestPortType {


    /**
     * Проверить подпись сообщения
     * 
     * @param testSignatureRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.signature_test.TestSignatureResponse
     * @throws Fault
     */
    @WebMethod(action = "urn:testSignature")
    @WebResult(name = "testSignatureResponse", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/signature-test/", partName = "testSignatureResponse")
    public TestSignatureResponse testSignature(
        @WebParam(name = "testSignatureRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/signature-test/", partName = "testSignatureRequest")
        TestSignatureRequest testSignatureRequest)
        throws Fault
    ;

}
