
package ru.gosuslugi.dom.schema.integration.msp_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MSPService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/msp-service/", wsdlLocation = "file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.0.0.3/hcs_wsdl_xsd_v.11.0.0.3/msp/hcs-msp-service.wsdl")
public class MSPService
    extends Service
{

    private final static URL MSPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MSPSERVICE_EXCEPTION;
    private final static QName MSPSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/msp-service/", "MSPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.11.0.0.3/hcs_wsdl_xsd_v.11.0.0.3/msp/hcs-msp-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MSPSERVICE_WSDL_LOCATION = url;
        MSPSERVICE_EXCEPTION = e;
    }

    public MSPService() {
        super(__getWsdlLocation(), MSPSERVICE_QNAME);
    }

    public MSPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MSPSERVICE_QNAME, features);
    }

    public MSPService(URL wsdlLocation) {
        super(wsdlLocation, MSPSERVICE_QNAME);
    }

    public MSPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MSPSERVICE_QNAME, features);
    }

    public MSPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MSPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MSPPort
     */
    @WebEndpoint(name = "MSPPort")
    public MSPPort getMSPPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/msp-service/", "MSPPort"), MSPPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MSPPort
     */
    @WebEndpoint(name = "MSPPort")
    public MSPPort getMSPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/msp-service/", "MSPPort"), MSPPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MSPSERVICE_EXCEPTION!= null) {
            throw MSPSERVICE_EXCEPTION;
        }
        return MSPSERVICE_WSDL_LOCATION;
    }

}
