
package ru.gosuslugi.dom.schema.integration.licenses_service_async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.AckRequest;
import ru.gosuslugi.dom.schema.integration.base.GetStateRequest;
import ru.gosuslugi.dom.schema.integration.licenses.ExportDisqualifiedPersonRequest;
import ru.gosuslugi.dom.schema.integration.licenses.ExportLicenseRequest;
import ru.gosuslugi.dom.schema.integration.licenses.GetStateResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LicensePortsTypeAsync", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/licenses-service-async/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.licenses.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.individual_registry_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface LicensePortsTypeAsync {


    /**
     * 
     * @param exporttLicenseRequestType
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportLicense")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportLicense(
        @WebParam(name = "exportLicenseRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/licenses/", partName = "exporttLicenseRequestType")
        ExportLicenseRequest exporttLicenseRequestType)
        throws Fault
    ;

    /**
     * 
     * @param exportDisqualifiedPersonRequestType
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.AckRequest
     * @throws Fault
     */
    @WebMethod(action = "urn:exportDisqualifiedPerson")
    @WebResult(name = "AckRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "AckRequest")
    public AckRequest exportDisqualifiedPerson(
        @WebParam(name = "exportDisqualifiedPersonRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/licenses/", partName = "exportDisqualifiedPersonRequestType")
        ExportDisqualifiedPersonRequest exportDisqualifiedPersonRequestType)
        throws Fault
    ;

    /**
     * 
     * @param getStateRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.licenses.GetStateResult
     * @throws Fault
     */
    @WebMethod(action = "urn:getState")
    @WebResult(name = "getStateResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/licenses/", partName = "getStateResult")
    public GetStateResult getState(
        @WebParam(name = "getStateRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "getStateRequest")
        GetStateRequest getStateRequest)
        throws Fault
    ;

}
