
package ru.gosuslugi.dom.schema.integration.organizations_registry_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegOrgService", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-service/", wsdlLocation = "file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.10.0.2.3/hcs_wsdl_xsd_v.10.0.2.3/organizations-registry/hcs-organizations-registry-service.wsdl")
public class RegOrgService
    extends Service
{

    private final static URL REGORGSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGORGSERVICE_EXCEPTION;
    private final static QName REGORGSERVICE_QNAME = new QName("http://dom.gosuslugi.ru/schema/integration/organizations-registry-service/", "RegOrgService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/work/GIS_MUP/\u0413\u0418\u0421%20\u0416\u041a\u0425_\u0418\u043d\u0442\u0435\u0433\u0440\u0430\u0446\u0438\u044f_v.10.0.2.3/hcs_wsdl_xsd_v.10.0.2.3/organizations-registry/hcs-organizations-registry-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGORGSERVICE_WSDL_LOCATION = url;
        REGORGSERVICE_EXCEPTION = e;
    }

    public RegOrgService() {
        super(__getWsdlLocation(), REGORGSERVICE_QNAME);
    }

    public RegOrgService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGORGSERVICE_QNAME, features);
    }

    public RegOrgService(URL wsdlLocation) {
        super(wsdlLocation, REGORGSERVICE_QNAME);
    }

    public RegOrgService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGORGSERVICE_QNAME, features);
    }

    public RegOrgService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegOrgService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegOrgPortsType
     */
    @WebEndpoint(name = "RegOrgPort")
    public RegOrgPortsType getRegOrgPort() {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/organizations-registry-service/", "RegOrgPort"), RegOrgPortsType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegOrgPortsType
     */
    @WebEndpoint(name = "RegOrgPort")
    public RegOrgPortsType getRegOrgPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dom.gosuslugi.ru/schema/integration/organizations-registry-service/", "RegOrgPort"), RegOrgPortsType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGORGSERVICE_EXCEPTION!= null) {
            throw REGORGSERVICE_EXCEPTION;
        }
        return REGORGSERVICE_WSDL_LOCATION;
    }

}
