
package ru.gosuslugi.dom.schema.integration.organizations_registry_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ru.gosuslugi.dom.schema.integration.base.ImportResult;
import ru.gosuslugi.dom.schema.integration.organizations_registry.ImportForeignBranchRequest;
import ru.gosuslugi.dom.schema.integration.organizations_registry.ImportSubsidiaryRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegOrgPortsType", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry-service/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.gosuslugi.dom.schema.integration.organizations_registry.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.nsi_base.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_registry_base.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    ru.gosuslugi.dom.schema.integration.organizations_base.ObjectFactory.class
})
public interface RegOrgPortsType {


    /**
     * импорт сведений об обособленном подразделении
     * 
     * @param importSubsidiaryRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importSubsidiary")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importSubsidiaryResult")
    public ImportResult importSubsidiary(
        @WebParam(name = "importSubsidiaryRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry/", partName = "importSubsidiaryRequest")
        ImportSubsidiaryRequest importSubsidiaryRequest)
        throws Fault
    ;

    /**
     * импорт сведений о филиале или представительстве иностранного юридического лица
     * 
     * @param importForeignBranchRequest
     * @return
     *     returns ru.gosuslugi.dom.schema.integration.base.ImportResult
     * @throws Fault
     */
    @WebMethod(action = "urn:importForeignBranch")
    @WebResult(name = "ImportResult", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/base/", partName = "importForeignBranchResult")
    public ImportResult importForeignBranch(
        @WebParam(name = "importForeignBranchRequest", targetNamespace = "http://dom.gosuslugi.ru/schema/integration/organizations-registry/", partName = "importForeignBranchRequest")
        ImportForeignBranchRequest importForeignBranchRequest)
        throws Fault
    ;

}
